### PR TITLE
Priority based route verification

### PR DESCRIPTION
**Pull request by jschummer**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89)

### CODE REVIEW

**Review by culka — COMMENTED** [review]
I've tried multiple times to break this in various ways and everything seems to work as it should :+1:

Nice work with the tests.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89#-:-N8OMOzZ8IIt4SnL3G5W:b-3phrqn)* status: 0 of 13 files reviewed, all discussions resolved

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @culka and @jschummer)

___
*[`migrations/generic/default/1657873981408_priority_based_route_verification/up.sql` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89#-N8OOuxn9MSLnc7DCFZr:-N8OOuxo-d9e3Nk4Imef:b-4a8615) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a469ed97b3ca694963a65dc938f38ddefe294627/migrations/generic/default/1657873981408_priority_based_route_verification/up.sql#L2)):*
> ```TSQL
> 
> CREATE FUNCTION journey_pattern.maximum_priority_validity_spans(
> ```

This function is currently used to fetch priority validity for a specific route, filtered_route_id in check_route_journey_pattern_refs below. It might be better to filter the initial query in this function by the route id/label.

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`migrations/generic/default/1657873981408_priority_based_route_verification/up.sql` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89#-N8OOuxn9MSLnc7DCFZr:-N8wA3qr9U_tRixHpt4t:bdstnh1) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a469ed97b3ca694963a65dc938f38ddefe294627/migrations/generic/default/1657873981408_priority_based_route_verification/up.sql#L2)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

This function is currently used to fetch priority validity for a specific route, filtered_route_id in check_route_journey_pattern_refs below. It might be better to filter the initial query in this function by the route id/label.
</blockquote></details>

I had tested some ways of potential optimizations of this, but postgresql was more clever and my optimizations did not bring any benefit.

Your suggestion sounds like I _might_ have tested it, but I'm not sure. I'll try it and will let you know if it made a difference.

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`migrations/generic/default/1657873981408_priority_based_route_verification/up.sql` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89#-N8OOuxn9MSLnc7DCFZr:-N8wzOxiENkmGqH5bomD:bmwi197) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/12cf52229ba1503c6f5f8546f2998ed8ae583b75/migrations/generic/default/1657873981408_priority_based_route_verification/up.sql#L2)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I had tested some ways of potential optimizations of this, but postgresql was more clever and my optimizations did not bring any benefit.

Your suggestion sounds like I _might_ have tested it, but I'm not sure. I'll try it and will let you know if it made a difference.
</blockquote></details>

It really looks like postgresql is already optimizing the queries such that only the relevant route is taken into account. Here some output of EXPLAIN:

1. Original SELECT call of check_route_journey_pattern_refs as seen in this PR:
cost=121.66..121.72

2. Passing filter_route_id to maximum_priority_validity_spans when fetching the route segments to check:
cost=121.67..121.73

3. Same as 2, but additionally removed the check_route_journey_pattern_refs's WHERE clause to filter the routes there:
cost=346.27..346.33

I'm not totally sure if 3 is doing what I expect, but even if the query is doing the right thing, it is way more expensive.

So is it acceptable to leave the PR as it is?

**Review by culka — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89#-:-N8x7cVd0ksJEAN1pv3Z:bnfp4nl)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @culka)

___
*[`migrations/generic/default/1657873981408_priority_based_route_verification/up.sql` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/89#-N8OOuxn9MSLnc7DCFZr:-N8x7EQm4MGiq7vsmiIl:b-8nvjh6) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/12cf52229ba1503c6f5f8546f2998ed8ae583b75/migrations/generic/default/1657873981408_priority_based_route_verification/up.sql#L2)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

It really looks like postgresql is already optimizing the queries such that only the relevant route is taken into account. Here some output of EXPLAIN:

1. Original SELECT call of check_route_journey_pattern_refs as seen in this PR:
cost=121.66..121.72

2. Passing filter_route_id to maximum_priority_validity_spans when fetching the route segments to check:
cost=121.67..121.73

3. Same as 2, but additionally removed the check_route_journey_pattern_refs's WHERE clause to filter the routes there:
cost=346.27..346.33

I'm not totally sure if 3 is doing what I expect, but even if the query is doing the right thing, it is way more expensive.

So is it acceptable to leave the PR as it is?
</blockquote></details>

Sounds really good, I can't really think of any other optimizations or improvements for this.

**Pull request merged**
