### PR TITLE
Add actions for to replace API endpoint

### PR DESCRIPTION
**Pull request by Perholehto**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/209)

### CODE REVIEW

**Review by culka — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/209#-:-NgrMI4t0mScXLLAgJN9:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Perholehto)

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/209)* status: all files reviewed, 1 unresolved discussion (waiting on @Perholehto)

___
*[`metadata/hsl/actions.graphql` line 12 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/209#-NgrMdXb58x2six6rPGI:-NgrMdXc2Gln_Ou-PoeB:bivt187) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1453a5ce18076c00119f52ced2cc6bbae8ed8406/metadata/hsl/actions.graphql#L12)):*
> ```GraphQL
>   toReplaceScheduleVehicleFrameIds(
>     arg1: ToReplaceScheduleVehicleFrameIdsInput!
>   ): ToReplaceScheduleVehicleFrameIdsOutput
> ```

Maybe change all terms in this PR from `ScheduleVehicleFrame` -> `VehicleScheduleFrame`

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/209)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @culka and @Leitsi)

___
*[`metadata/hsl/actions.graphql` line 12 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/209#-NgrMdXb58x2six6rPGI:-NgsR9Ec5F55MwyMylTU:b-bt4phy) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/1453a5ce18076c00119f52ced2cc6bbae8ed8406/metadata/hsl/actions.graphql#L12)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Maybe change all terms in this PR from `ScheduleVehicleFrame` -> `VehicleScheduleFrame`
</blockquote></details>

Good catch, updated

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/209#-:-Ngw50CK4xhYtgMum5OK:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
