### PR TITLE
Optimize scheduled_stop_point_in_journey_pattern insert

### PR DESCRIPTION
**Pull request by Leitsi**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)

### CODE REVIEW

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`migrations/generic/default/1000000000000_R_before_migrate/up.sql` line 110 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUVZ3sc-lwEhXf_kH6C:-NUVZ3sc-lwEhXf_kH6D:b3meswd) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/generic/default/1000000000000_R_before_migrate/up.sql#L110)):*
> ```TSQL
>   FROM pg_proc
>   WHERE pronamespace = ANY(target_schemas::regnamespace[])
>   AND provolatile NOT IN ('i');
> ```

These need to be deleted manually if needed?

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`migrations/routesdb-dump.sql` line 3592 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUuq_db6WNVqRNJR4_m:-NUuq_dc0yh7tP-DhmtI:b-il0ma0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/routesdb-dump.sql#L3592)):*
> ```TSQL
> 
> CREATE FUNCTION service_pattern.maybe_append_new_scheduled_stop_point(new_scheduled_stop_point_id uuid DEFAULT NULL::uuid, new_located_on_infrastructure_link_id uuid DEFAULT NULL::uuid, new_measured_location public.geography DEFAULT NULL::public.geography, new_direction text DEFAULT NULL::text, new_label text DEFAULT NULL::text, new_validity_start date DEFAULT NULL::date, new_validity_end date DEFAULT NULL::date, new_priority integer DEFAULT NULL::integer) RETURNS TABLE(scheduled_stop_point_id uuid, measured_location public.geography, located_on_infrastructure_link_id uuid, direction text, label text, validity_start date, validity_end date, priority integer, relative_distance_from_infrastructure_link_start double precision, closest_point_on_infrastructure_link public.geography)
>     LANGUAGE plpgsql STABLE
> ```

Since the inner code (query part) of this function is now pure SQL, I prefer to change the language from `plpgsql` to `sql`. To do this, you need to remove the `BEGIN` keyword and its `END` counterpart and `RETURN QUERY`.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`migrations/routesdb-dump.sql` line 3612 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUuupmrAf6cVC0DGT-S:-NUuupmrAf6cVC0DGT-T:b-x61vna) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/routesdb-dump.sql#L3612)):*
> ```TSQL
>         il.infrastructure_link_id = new_located_on_infrastructure_link_id
>       ELSE
>         il.infrastructure_link_id = NULL -- Matches nothing.
> ```

`= NULL` always results to `false`. You should use `IS NULL` syntax. But it looks like the whole `ELSE` branch could be simplified to just `ELSE false`.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`migrations/routesdb-dump.sql` line 2362 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUuxAFD5p7ZLTjS7eGj:-NUuxAFD5p7ZLTjS7eGk:br7yzaf) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/routesdb-dump.sql#L2362)):*
> ```TSQL
>         WHERE replace_scheduled_stop_point_id IS NULL
>            OR ssp.scheduled_stop_point_id != replace_scheduled_stop_point_id
>       UNION ALL
> ```

I think `UNION ALL` could be changed to plain `UNION` as we probably wouldn't want to have duplicates (accumulated from both side of the union operation) if there were any at all.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: 2 of 5 files reviewed, 10 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql` line 378 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUuzLpk1pRtBOWdz0Wk:-NUuzLpk1pRtBOWdz0Wl:bkvctpm) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql#L378)):*
> ```TSQL
>         WHERE replace_scheduled_stop_point_id IS NULL
>         OR ssp.scheduled_stop_point_id != replace_scheduled_stop_point_id
>       UNION ALL
> ```

I'd add a comment that `UNION ALL` is an optimization over plain `UNION` (avoid sorting occurring within it) since we know there are no duplicates (or do we?).

**Review by jarkkoka — CHANGES_REQUESTED** [review]
Ok i completed the review now. Left some remarks but overall it looks well thought out!

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-:-NUvDSrb9XZxk6F6Y7F2:b-hotqx5)* status: 2 of 5 files reviewed, 10 unresolved discussions (waiting on @culka and @Leitsi)

**Review by jarkkoka — CHANGES_REQUESTED** [review]
Nice addition to relocate the immutable SQL functions and change their handling. Overall, very good job!

Still left some minor remarks...

> Reviewed 1 of 2 files at r16, 6 of 6 files at r17, 1 of 3 files at r20, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-:-NUzmiyf5dMh-t9-wbx1:b934f5r)* status: 9 of 11 files reviewed, 13 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql` line 1 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUaWMXL12reyOU91wWn:-NV-1Lcm2ScQjYenKjdJ:b-hkq1qz) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql#L1)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

If this view is only intended to be called internally (by trigger functions), I suggest moving it to the `internal_service_pattern` schema, which is private and not intended to be exposed to the GraphQL API.
</blockquote></details>

It seems this earlier remark is still unaddressed...

I have another problem with the function name, which I think is a bit detrimental to the good flow of code reading (at call sites). Therefore, I suggest naming it to `new_scheduled_stop_point_if_id_given`.
___
*[`migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql` line 55 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUzmFWy9n5NDxSf9P0Z:-NUzmFWy9n5NDxSf9P0_:bbqkd6c) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/e7092327f4de480781199f55c1df6ad95994886d/migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql#L55)):*
> ```TSQL
>   WHERE
>     CASE
>       WHEN new_scheduled_stop_point_id IS NOT NULL THEN
> ```

It seems that WHERE predicate could be further simplified to form (reducing CASE-WHEN structure out):

```sql
    WHERE new_scheduled_stop_point_id IS NOT NULL AND new_located_on_infrastructure_link_id = il.infrastructure_link_id
```

or maybe even

```sql
    WHERE new_scheduled_stop_point_id IS DISTINCT FROM il.infrastructure_link_id
```
___
*[`migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql` line 49 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NV-2EB3-EJiAmTd4D4P:-NV-2EB3-EJiAmTd4D4Q:b-s7k5dh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/e7092327f4de480781199f55c1df6ad95994886d/migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql#L49)):*
> ```TSQL
>       SELECT * FROM service_pattern.scheduled_stop_points_with_infra_link_data ssp
>         WHERE replace_scheduled_stop_point_id IS NULL
>            OR ssp.scheduled_stop_point_id != replace_scheduled_stop_point_id
> ```

The following code could be made more concise.

```sql
    WHERE replace_scheduled_stop_point_id IS NULL
        OR ssp.scheduled_stop_point_id != replace_scheduled_stop_point_id
```

with this (if it does not adversely affect performance):

```sql
    WHERE replace_scheduled_stop_point_id IS DISTINCT FROM ssp.scheduled_stop_point_id
```
___
*[`migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql` line 326 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NV-2rM_CDRA3o8ZYWUi:-NV-2rM_CDRA3o8ZYWUj:b-s7k5dh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/e7092327f4de480781199f55c1df6ad95994886d/migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql#L326)):*
> ```TSQL
>   ssp_with_new AS (
>       SELECT * FROM service_pattern.scheduled_stop_points_with_infra_link_data ssp
>         WHERE replace_scheduled_stop_point_id IS NULL
> ```

The following code could be made more concise.

```sql
    WHERE replace_scheduled_stop_point_id IS NULL
        OR ssp.scheduled_stop_point_id != replace_scheduled_stop_point_id
```

with this (if it does not adversely affect performance):

```sql
    WHERE replace_scheduled_stop_point_id IS DISTINCT FROM ssp.scheduled_stop_point_id
```

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: 9 of 11 files reviewed, 13 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql` line 55 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUzmFWy9n5NDxSf9P0Z:-NV-4BxID0va_4_rufDF:b-yh0dz5) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/e7092327f4de480781199f55c1df6ad95994886d/migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql#L55)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It seems that WHERE predicate could be further simplified to form (reducing CASE-WHEN structure out):

```sql
    WHERE new_scheduled_stop_point_id IS NOT NULL AND new_located_on_infrastructure_link_id = il.infrastructure_link_id
```

or maybe even

```sql
    WHERE new_scheduled_stop_point_id IS DISTINCT FROM il.infrastructure_link_id
```
</blockquote></details>

Oops. The second suggestion was wrong! Fix: `IS DISTINCT FROM` ->`IS NOT DISTINCT FROM`

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: 5 of 11 files reviewed, 13 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql` line 1 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUaWMXL12reyOU91wWn:-NV3pjFu5CfZDJ8wgz8H:b-y302bf) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql#L1)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Possibly. But same rationale would apply to the function below, and all the other functions used eg. in these validations. Overall it feels like not much attention has been what gets exposed from GraphQL. Moving just this view would be slightly weird exception, and doing any bigger refactoring i.e. moving all non-public stuff to private schemas should not be part of this PR.
</blockquote></details>

:ok_hand: will rename.
___
*[`migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql` line 55 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUzmFWy9n5NDxSf9P0Z:-NV3oM603vhXK-72uf3W:b-d214st) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/e7092327f4de480781199f55c1df6ad95994886d/migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql#L55)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Oops. The second suggestion was wrong! Fix: `IS DISTINCT FROM` ->`IS NOT DISTINCT FROM`
</blockquote></details>

True, could implement the first suggestion.

I don't think the second suggestion is an improvement, the intent is not clear anymore. Also I remember reading recently that `IS NOT DISTINCT FROM` might not be a good idea since query planner tends to skip index and do seq scan instead. https://philbooth.me/blog/nine-ways-to-shoot-yourself-in-the-foot-with-postgresql point 9.

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 2 of 5 files at r13, 2 of 6 files at r25, 1 of 3 files at r28, 2 of 2 files at r31, 1 of 1 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: all files reviewed, 5 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`migrations/routesdb-dump.sql` line 2362 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUuxAFD5p7ZLTjS7eGj:-NV4254XDAMKjDEmk1IK:b-lb6cr1) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/routesdb-dump.sql#L2362)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

No duplicates here, just like in the other similar case in `prioritized_ssp_with_new`, since the "new SSP" part only (possibly) returns a fake SSP with new generated id.
</blockquote></details>

Ok. :+1: 
___
*[`migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql` line 1 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUaWMXL12reyOU91wWn:-NV42Vd91Sxwr2o3D7tC:b-uupnh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql#L1)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

:ok_hand: will rename.
</blockquote></details>

Ok. Maybe some internal/public separation should be carried out in a separate PR. :+1: 
___
*[`migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql` line 51 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUaYlKuEAnmoKtE6LBw:-NV43ZD50Dw02QMoSIYx:bn95mpa) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql#L51)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Not quite sure. One guess: it's not actually used, just here to mimic scheduled stop points. In fact, I don't see the `closest_point_on_infrastructure_link` column being used for anything on DB side. So could just try to remove it altogether, from this view and function.
</blockquote></details>

Ok, if the function is not exposed (or intended to be exposed) to GraphQL, the last two fields can be removed as they require computation that may be unnecessary.

This is another optimisation you can consider.
___
*[`migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql` line 53 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUaXA2bA-h8uuUutvdP:-NV46TWDEcgc6ge-liNb:b-ucfknh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4b9c40dfbf24fbced65bac8eaffa3ca4d2cda5fd/migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql#L53)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

:heavy_check_mark: added.
</blockquote></details>

Thanks!
___
*[`migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql` line 378 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUuzLpk1pRtBOWdz0Wk:-NV47CsN2V6gyeFoqgB7:b-ucfknh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql#L378)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

> or do we?

Looks like it to me.

:ok_hand: added.
</blockquote></details>

Thanks!
___
*[`migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql` line 455 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUukyKG0-HtPCdgbHXG:-NV47GHi0hazVWOWhvS2:b-lb6cr1) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql#L455)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Good point, makes more sense. No difference in performance either, fixed.
</blockquote></details>

Ok. :+1:

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: all files reviewed, 3 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql` line 51 at r12](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NUaYlKuEAnmoKtE6LBw:-NV4JV5TDYdNQTp9FdFq:b-fizo3q) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/425ee7ce49920af91588cc93e0b261df09ee0ffc/migrations/generic/default/2000000000003_R_after_migrate_create_service_pattern_1/up.sql#L51)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, if the function is not exposed (or intended to be exposed) to GraphQL, the last two fields can be removed as they require computation that may be unnecessary.

This is another optimisation you can consider.
</blockquote></details>

Removed.

`relative_distance_from_infrastructure_link_start` is actually used.
___
*[`migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql` line 49 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NV-2EB3-EJiAmTd4D4P:-NV4JoqH3G5IwS8kQn9D:b-j7ekyl) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/e7092327f4de480781199f55c1df6ad95994886d/migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql#L49)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The following code could be made more concise.

```sql
    WHERE replace_scheduled_stop_point_id IS NULL
        OR ssp.scheduled_stop_point_id != replace_scheduled_stop_point_id
```

with this (if it does not adversely affect performance):

```sql
    WHERE replace_scheduled_stop_point_id IS DISTINCT FROM ssp.scheduled_stop_point_id
```
</blockquote></details>

Changed, didn't seem to be slower.
___
*[`migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql` line 326 at r24](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179#-NV-2rM_CDRA3o8ZYWUi:-NV4JvVeE9IN4gd1gbYH:b-j7ekyl) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/e7092327f4de480781199f55c1df6ad95994886d/migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql#L326)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The following code could be made more concise.

```sql
    WHERE replace_scheduled_stop_point_id IS NULL
        OR ssp.scheduled_stop_point_id != replace_scheduled_stop_point_id
```

with this (if it does not adversely affect performance):

```sql
    WHERE replace_scheduled_stop_point_id IS DISTINCT FROM ssp.scheduled_stop_point_id
```
</blockquote></details>

Changed, didn't seem to be slower.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 4 files at r33, 1 of 1 files at r38, 1 of 2 files at r40, 2 of 2 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/179)* status: all files reviewed, 1 unresolved discussion (waiting on @culka)

**Pull request merged**
