### PR TITLE
Add config for including typings with data inserter

### PR DESCRIPTION
**Pull request by HenrikHartiala**
This data inserter is planned to be used as the main test data inserter for all the repositories, but currently the other repositories could not use this yet since the builders couldn't figure out the typings on this sub module.

Resolves HSLdevcom/jore4#1427

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200)* status: all files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200#-NerXNK01XuA7ryBpC5o):*
`Clearance` = eg. `discount`, `clarity` is probably what you mean here.



_Suggestion:_
```
for clarity
```
___
*[`test/hasura/timetables-data-inserter/generic/data-insert.ts` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200#-NeranidBRvzymRFlgH8:-NeranidBRvzymRFlgH9:b-qzrg9f) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/7346c9272732e61efe8209406693422db5ccef51/test/hasura/timetables-data-inserter/generic/data-insert.ts#L21)):*
> ```XML
>   closeDbConnection(dbConnection);
>   return builtDataset;
> };
> ```

This could just use the `insertGenericDataset` method. Also maybe rename `result`.



_Suggestion:_
```XML
) => {
  const datasetInput = parseGenericDatasetJson(input);
  return insertGenericDataset(datasetInput, dbConfig);
};
```
___
*[`test/hasura/timetables-data-inserter/hsl/data-insert.ts` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200#-NerbC9w03wJuvMBNHut:-NerbC9w03wJuvMBNHuu:bcslt2z) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/7346c9272732e61efe8209406693422db5ccef51/test/hasura/timetables-data-inserter/hsl/data-insert.ts#L13)):*
> ```XML
>   input: string,
>   dbConfig: ConnectionConfig = timetablesDbConfig,
> ) => {
> ```

Same here as on the generic side, use `insertHslDataset` and renae `result`.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`-- commits` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200#-NerXNK01XuA7ryBpC5o):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

`Clearance` = eg. `discount`, `clarity` is probably what you mean here.
</blockquote></details>

Ah yes, exactly! Thanks
___
*[`test/hasura/timetables-data-inserter/generic/data-insert.ts` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200#-NeranidBRvzymRFlgH8:-Nerdn5w1ECV0FyDsgln:bjk9oqg) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/7346c9272732e61efe8209406693422db5ccef51/test/hasura/timetables-data-inserter/generic/data-insert.ts#L21)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This could just use the `insertGenericDataset` method. Also maybe rename `result`.
</blockquote></details>

Ah good point! Thanks!
___
*[`test/hasura/timetables-data-inserter/hsl/data-insert.ts` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200#-NerbC9w03wJuvMBNHut:-NerdtOY3X6syswFvEO-:b4putsz) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/7346c9272732e61efe8209406693422db5ccef51/test/hasura/timetables-data-inserter/hsl/data-insert.ts#L13)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Same here as on the generic side, use `insertHslDataset` and renae `result`.
</blockquote></details>

:ok_hand:

**Review by Leitsi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @HenrikHartiala)

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/200#-:-NerespAABb8AHVp2_gm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @HenrikHartiala)

**Pull request merged**
