### PR TITLE
Refactor passing time validation triggers to use existing validation triggers

### PR DESCRIPTION
**Pull request by Leitsi**
Reduce duplication, and allow triggering validation in more cases.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213)* status: 1 of 4 files reviewed, 17 unresolved discussions (waiting on @Leitsi)

___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9CjAm27rYKz_kRttL:-Ni9CjAm27rYKz_kRttM:b-eo9j87) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L1)):*
> ```TSQL
> -- This migration contains necessary triggers for queueing modified rows for later validation.
> ```

Very nice description! :+1: 
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9kV043qkhu1wZcM3B:-Ni9kV043qkhu1wZcM3C:b-u7zgkc) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L12)):*
> ```TSQL
> -- * Note: these need to be separate for each operation
> --         because PostgreSQL doesn't accept eg. INSERT OR UPDATE here
> -- * Note: this is NOT DEFERRABLE (default)
> ```

"Note: this is NOT DEFERRABLE (default)"

I would change this to:

"Note: Called immediately after insert/update/delete statement (because NOT DEFERRABLE is in effect by default)"
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9Cap8DJZdqrROzm8H:-Ni9Cap8DJZdqrROzm8I:bc2pj1x) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L21)):*
> ```TSQL
> -- 2. process_queued_validation_on_xxx_trigger
> -- * Executed at end of transaction (INITIALLY DEFERRED).
> -- * Internal_utils.queued_validations_already_processed handles that we only do the validation once,
> ```

`internal_utils` (all lowercase)
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 152 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9FBTN4keiF7fyEFBq:-Ni9FBTN4keiF7fyEFBr:b-rmfhyw) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L152)):*
> ```TSQL
>   $$;
> COMMENT ON FUNCTION journey_pattern.queue_validation_by_jpr_id()
> IS 'Queue modified vehicle schedule frames for validation which is performed at the end of transaction.';
> ```

Noticed copy-paste error here, should be "journey pattern refs"
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 196 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9_3-U49xnHApEhWO-:-Ni9_3-U49xnHApEhWO0:bk36kvg) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L196)):*
> ```TSQL
>   EXECUTE FUNCTION vehicle_schedule.queue_validation_by_vsf_id();
> COMMENT ON TRIGGER queue_vsf_validation_on_insert_trigger ON vehicle_schedule.vehicle_schedule_frame
> IS 'Trigger for queuing modified vehicle schedule frames for later validation.
> ```

perhaps "inserted" instead of "modified" to distinguish from the update trigger.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 206 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9Zvvt64AZmqlMzLd5:-Ni9Zvvt64AZmqlMzLd6:b-mpmco9) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L206)):*
> ```TSQL
>   EXECUTE FUNCTION vehicle_schedule.queue_validation_by_vsf_id();
> COMMENT ON TRIGGER queue_vsf_validation_on_update_trigger ON vehicle_schedule.vehicle_schedule_frame
> IS 'Trigger for queuing modified vehicle schedule frames for later validation.
> ```

perhaps "updated" instead of "modified" to distinguish from the insert trigger.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 239 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9_EgN0IJ6czL1_YEi:-Ni9_EgN0IJ6czL1_YEj:bk36kvg) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L239)):*
> ```TSQL
>   EXECUTE FUNCTION vehicle_journey.queue_validation_by_vj_id();
> COMMENT ON TRIGGER queue_vj_validation_on_insert_trigger ON vehicle_journey.vehicle_journey
> IS 'Trigger for queuing modified vehicle journeys for later validation.
> ```

perhaps "inserted" instead of "modified" to distinguish from the update trigger.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9_IxuDjL_PhjQmqMa:-Ni9_IxuDjL_PhjQmqMb:b-mpmco9) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L249)):*
> ```TSQL
>   EXECUTE FUNCTION vehicle_journey.queue_validation_by_vj_id();
> COMMENT ON TRIGGER queue_vj_validation_on_update_trigger ON vehicle_journey.vehicle_journey
> IS 'Trigger for queuing modified vehicle journeys for later validation.
> ```

perhaps "updated" instead of "modified" to distinguish from the insert trigger.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 254 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9b9EQDhIQ4kWnpJks:-Ni9b9EQDhIQ4kWnpJkt:b-lw3vsb) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L254)):*
> ```TSQL
> -- journey_pattern_ref:
> DROP TRIGGER IF EXISTS queue_jpr_validation_on_update_trigger ON journey_pattern.journey_pattern_ref;
> CREATE TRIGGER queue_jpr_validation_on_update_trigger
> ```

Currently, the `journey_pattern_ref` table is never updated in the code. Although I'm not sure if we'll want to do updates in the future.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 260 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9_O5P-mSDqUfF0uPT:-Ni9_O5P-mSDqUfF0uPU:b-mpmco9) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L260)):*
> ```TSQL
>   EXECUTE FUNCTION journey_pattern.queue_validation_by_jpr_id();
> COMMENT ON TRIGGER queue_jpr_validation_on_update_trigger ON journey_pattern.journey_pattern_ref
> IS 'Trigger for queuing modified journey pattern refs for later validation.
> ```

perhaps "updated" instead of "modified" to distinguish from the insert trigger.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 265 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9dKwREr2cKvBp3oR9:-Ni9dKwREr2cKvBp3oRA:bmwuxz0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L265)):*
> ```TSQL
> DROP TRIGGER IF EXISTS queue_jpr_validation_on_insert_trigger ON journey_pattern.journey_pattern_ref;
> CREATE TRIGGER queue_jpr_validation_on_insert_trigger
>   AFTER INSERT ON journey_pattern.journey_pattern_ref
> ```

As a side note, the `journey_pattern_ref` table is no longer created in the same transaction where rows are added to the `vehicle_schedule_frame` table (or any timetable changes or done). Not sure if this should affect the trigger logic.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 270 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9_QB8DoDYpFAtvoTc:-Ni9_QBA-l2-UogUcg92:bk36kvg) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L270)):*
> ```TSQL
>   EXECUTE FUNCTION journey_pattern.queue_validation_by_jpr_id();
> COMMENT ON TRIGGER queue_jpr_validation_on_insert_trigger ON journey_pattern.journey_pattern_ref
> IS 'Trigger for queuing modified journey pattern refs for later validation.
> ```

perhaps "inserted" instead of "modified" to distinguish from the update trigger.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 309 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9cMr4BLVSqh1oBgk0:-Ni9cMr4BLVSqh1oBgk1:b-8z79d7) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L309)):*
> ```TSQL
> DROP TRIGGER IF EXISTS queue_jpr_validation_on_ssp_update_trigger ON service_pattern.scheduled_stop_point_in_journey_pattern_ref;
> CREATE TRIGGER queue_jpr_validation_on_ssp_update_trigger
>   AFTER UPDATE ON service_pattern.scheduled_stop_point_in_journey_pattern_ref
> ```

Currently, the `scheduled_stop_point_in_journey_pattern_ref` table is never updated in the code. Although I'm not sure if we'll want to do updates in the future.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 319 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9fo4O0SYD0oZPrURX:-Ni9fo4O0SYD0oZPrURY:b-dfl91g) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L319)):*
> ```TSQL
> DROP TRIGGER IF EXISTS queue_jpr_validation_on_ssp_insert_trigger ON service_pattern.scheduled_stop_point_in_journey_pattern_ref;
> CREATE TRIGGER queue_jpr_validation_on_ssp_insert_trigger
>   AFTER INSERT ON service_pattern.scheduled_stop_point_in_journey_pattern_ref
> ```

As a side note, the `scheduled_stop_point_in_journey_pattern_ref` table is no longer created in the same transaction where rows are added to the `vehicle_schedule_frame` table (or any timetable changes or done). Not sure if this should affect the trigger logic.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 374 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9lZsM8vWojz5FHjsp:-Ni9lZsM8vWojz5FHjsq:b-byrlir) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L374)):*
> ```TSQL
> DROP TRIGGER IF EXISTS process_queued_validation_on_jpr_trigger ON journey_pattern.journey_pattern_ref;
> CREATE CONSTRAINT TRIGGER process_queued_validation_on_jpr_trigger
>   AFTER UPDATE ON journey_pattern.journey_pattern_ref
> ```

You also currently have a statement-level `AFTER INSERT` trigger on the `journey_pattern_ref` table.  Is there any reason to ignore it here?
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 393 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9mjLi619IaNjU6w8a:-Ni9mjLi619IaNjU6w8b:b-qm8tdk) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L393)):*
> ```TSQL
>     This trigger will cause those vehicle journeys to be checked, whose ID was queued to be checked by a statement level trigger.';
> 
> DROP TRIGGER IF EXISTS validate_passing_times_sequence_trigger ON service_pattern.scheduled_stop_point_in_journey_pattern_ref;
> ```

You drop the previously re-created trigger??
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 394 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9mpPk8IaD9gMfAn8A:-Ni9mpPk8IaD9gMfAn8B:b-d5cg3g) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L394)):*
> ```TSQL
> 
> DROP TRIGGER IF EXISTS validate_passing_times_sequence_trigger ON service_pattern.scheduled_stop_point_in_journey_pattern_ref;
> CREATE CONSTRAINT TRIGGER validate_passing_times_sequence_trigger
> ```

You re-define the previously created trigger??

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213)* status: 1 of 4 files reviewed, 18 unresolved discussions (waiting on @Leitsi)

___
*[`migrations/generic/timetables/2000000000003_R_after_migrate_create_passing_times/up.sql` line 92 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9sRwf0K5qbFm9xQPv:-Ni9sRwf0K5qbFm9xQPw:b-l4vyeg) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000003_R_after_migrate_create_passing_times/up.sql#L92)):*
> ```TSQL
>   in same order by passing_time as their corresponding stop points (scheduled_stop_point_in_journey_pattern_ref).';
> 
> CREATE OR REPLACE FUNCTION passing_times.validate_passing_time_sequences() RETURNS VOID
> ```

The accepted convention (in this project) in SQL migrations is to put types in lowercase.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213)* status: 1 of 4 files reviewed, 18 unresolved discussions (waiting on @Leitsi)

___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 254 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9b9EQDhIQ4kWnpJks:-Ni9v6_K7PGAeg0qLepI:bq38zq3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L254)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Currently, the `journey_pattern_ref` table is never updated in the code. Although I'm not sure if we'll want to do updates in the future.
</blockquote></details>

I will complete the previous comment. Currently, when exporting a route to Hastus, it results in a new row being created in the `journey_pattern_ref` table. Previously created rows are not updated.

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213)* status: 0 of 5 files reviewed, 18 unresolved discussions (waiting on @jarkkoka)

___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9kV043qkhu1wZcM3B:-NiArQ2i2VvIg_QjZjHX:bqv0zu8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"Note: this is NOT DEFERRABLE (default)"

I would change this to:

"Note: Called immediately after insert/update/delete statement (because NOT DEFERRABLE is in effect by default)"
</blockquote></details>

Good suggestion, changed.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9Cap8DJZdqrROzm8H:-NiAs4UkE38j7oXzznvY:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`internal_utils` (all lowercase)
</blockquote></details>

Done.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 152 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9FBTN4keiF7fyEFBq:-NiAsW7c9rLHlAPe7t3K:b-vlm2yz) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L152)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Noticed copy-paste error here, should be "journey pattern refs"
</blockquote></details>

Good catch :thumbsup: 
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 196 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9_3-U49xnHApEhWO-:-NiAyVgE5Rrw9UWfphkb:buzcw0n) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L196)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

perhaps "inserted" instead of "modified" to distinguish from the update trigger.
</blockquote></details>

:heavy_check_mark: 
Went through these and changed all to match the operation on each trigger.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 254 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9b9EQDhIQ4kWnpJks:-NiAAfbB8pKgFpgIhfR_:b1pjh1p) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L254)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I will complete the previous comment. Currently, when exporting a route to Hastus, it results in a new row being created in the `journey_pattern_ref` table. Previously created rows are not updated.
</blockquote></details>

Perhaps, but nothing prevents it from being updated, eg. via GraphQL.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 265 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9dKwREr2cKvBp3oR9:-NiAAWPGD_h0_albouvV:b-ay5vp0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L265)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

As a side note, the `journey_pattern_ref` table is no longer created in the same transaction where rows are added to the `vehicle_schedule_frame` table (or any timetable changes or done). Not sure if this should affect the trigger logic.
</blockquote></details>

Shouldn't make a difference. Some validations might be ran more than once if multiple transactions are used.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 309 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9cMr4BLVSqh1oBgk0:-NiA88Gl6scynIqnvPac:b17tux5) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L309)):*
> `scheduled_stop_point_in_journey_pattern_ref` is designed to be immutable and should never be updated.
If this is the case then modifications should probably be prevented somehow. Nothing prevents these being modified eg. via GraphQL.

Not in scope of this PR to change this.

When these validations were originally implemented it was specified that they need to be ran in all DB operations, and the triggers were implemented accordingly.
A great deal of effort went into making sure all of this works.
The intent of this PR was not to change their functionality.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 319 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9fo4O0SYD0oZPrURX:-NiA736H7oDXwcbng3ur:b-ay5vp0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L319)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

As a side note, the `scheduled_stop_point_in_journey_pattern_ref` table is no longer created in the same transaction where rows are added to the `vehicle_schedule_frame` table (or any timetable changes or done). Not sure if this should affect the trigger logic.
</blockquote></details>

Shouldn't make a difference. Some validations might be ran more than once if multiple transactions are used.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 374 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9lZsM8vWojz5FHjsp:-NiAtgUw7DJxrNxs0WnC:b4koi4t) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L374)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You also currently have a statement-level `AFTER INSERT` trigger on the `journey_pattern_ref` table.  Is there any reason to ignore it here?
</blockquote></details>

No reason, looks like a bug to me. The other trigger is useless without a matching deferred trigger. Added.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 393 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9mjLi619IaNjU6w8a:-NiA7oEd2mY3V-uFQyO_:bbfaxya) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L393)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You drop the previously re-created trigger??
</blockquote></details>

Nope. This is on different schema than the trigger created above.

Meant to rename these, like I did  for the queue triggers, but forgot to do that apparently. Fixed.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 394 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9mpPk8IaD9gMfAn8A:-NiA7rFH33qO74q357pw:bsjte78) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L394)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You re-define the previously created trigger??
</blockquote></details>

See above comment.
___
*[`migrations/generic/timetables/2000000000003_R_after_migrate_create_passing_times/up.sql` line 92 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9sRwf0K5qbFm9xQPv:-NiAx-YI5vtZWV26VEKD:byu0wld) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000003_R_after_migrate_create_passing_times/up.sql#L92)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The accepted convention (in this project) in SQL migrations is to put types in lowercase.
</blockquote></details>

:thumbsup: Fixed. Looks to be that way in PostgreSQL documentation as well, for example.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213)* status: all files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 254 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9b9EQDhIQ4kWnpJks:-NiDhtsfAgiCHG7uuXp7:b-onn3eg) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L254)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Perhaps, but nothing prevents it from being updated, eg. via GraphQL.
</blockquote></details>

Yes, maybe it's better to play it safe.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 265 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9dKwREr2cKvBp3oR9:-NiDisIDDLnS6wkusW_J:b2nhll9) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L265)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Shouldn't make a difference. Some validations might be ran more than once if multiple transactions are used.
</blockquote></details>

Ok.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 309 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-Ni9cMr4BLVSqh1oBgk0:-NiDtAQQ0pDKmP8CpDEF:bezduw5) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a20b1b6a473980d7c4b6c093dbe2bbc2394c6140/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L309)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

> `scheduled_stop_point_in_journey_pattern_ref` is designed to be immutable and should never be updated.
If this is the case then modifications should probably be prevented somehow. Nothing prevents these being modified eg. via GraphQL.

Not in scope of this PR to change this.

When these validations were originally implemented it was specified that they need to be ran in all DB operations, and the triggers were implemented accordingly.
A great deal of effort went into making sure all of this works.
The intent of this PR was not to change their functionality.
</blockquote></details>

Ok. We can deal with these in another context.
___
*[`migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql` line 217 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-NiDsriy0OvhiSzth3J8:-NiDsriy0OvhiSzth3J9:bvi3gtw) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/8c4d957c887d45b50955f97378210623ae454427/migrations/generic/timetables/2000000000001_R_after_migrate_create_validation_queue_objects/up.sql#L217)):*
> ```TSQL
>   EXECUTE FUNCTION vehicle_service.queue_validation_by_vs_id();
> COMMENT ON TRIGGER queue_vs_validation_on_update_trigger ON vehicle_service.vehicle_service
> IS 'Trigger for queuing updated vehicle schedules for later validation.
> ```

"vehicle schedules" -> "vehicle services"

**Review by jarkkoka — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/213#-:-NiEDhak9bqRp0jQRfSl:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
