### PR TITLE
Contract fields for timetables

### PR DESCRIPTION
**Pull request by culka**
Add contract fields to vehicle journeys in HSL schema.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/217)

### CODE REVIEW

**Review by Leitsi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/217#-:-NmFRTlo0D6aKc5lYcug:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @culka)

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/217)* status: all files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/217#-NmF_LuXCEpfjsxf99jj):*
Some of these descriptions could be more like in the form of what was done and/or explaining the reason more thoroughly. I mean these are good small commits, might not need a description at all, but just saying that "perhaps now a bit easier to understand", "since we might be enhanching these on HSL side" and "mostly clarify next commit" do not provide very much value after these commits are pushed to main.

One reasoning for this is that there is this nice feature on VS code for example, that you can target a line of code and intellisense shows the commit details for that line of code and the commit description might help to understand parts of the code.

Not putting this as blocking comment, since the commits themselves were pretty clear and simple :muscle: , but something to consider in the future
___
*[`migrations/seed-data/timetables/2524600900000_seed-timetables/up.sql` line 77 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/217#-NmFTftp99fwDTPfsZKE:-NmFTftp99fwDTPfsZKF:b9dq631) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/efbdf2459652b91c8214e1ab4531667987e5007c/migrations/seed-data/timetables/2524600900000_seed-timetables/up.sql#L77)):*
> ```TSQL
> VALUES
>   -- lähtö1
>   ('f8cfea28-29b8-4495-a707-93aea5673b06', '77a30292-807a-4cce-b4e2-e95049d3f096', 'a77a5e0c-9d49-4ecc-8dd6-0f63b079a11d', 'SUMMER23'),
> ```

NIT, Is this a realistic contract number? If it's not then I would probably change this to something that would not get confused with any of the timetable attributes. Or maybe add CONTRACT to post or prefix.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/217)* status: all files reviewed, 2 unresolved discussions (waiting on @culka and @HenrikHartiala)

___
*[`migrations/seed-data/timetables/2524600900000_seed-timetables/up.sql` line 77 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/217#-NmFTftp99fwDTPfsZKE:-NmFcIbGAp39FZ_Bkoly:bjhzymf) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/efbdf2459652b91c8214e1ab4531667987e5007c/migrations/seed-data/timetables/2524600900000_seed-timetables/up.sql#L77)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, Is this a realistic contract number? If it's not then I would probably change this to something that would not get confused with any of the timetable attributes. Or maybe add CONTRACT to post or prefix.
</blockquote></details>

I have this same impression. `SUMMER23` is more like a season, not a contract.

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/217)* status: 6 of 30 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala, @jarkkoka, and @Leitsi)

___
*[`migrations/seed-data/timetables/2524600900000_seed-timetables/up.sql` line 77 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/217#-NmFTftp99fwDTPfsZKE:-NmFkTa52NR6f9x6Ck08:b-3w7jih) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/efbdf2459652b91c8214e1ab4531667987e5007c/migrations/seed-data/timetables/2524600900000_seed-timetables/up.sql#L77)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I have this same impression. `SUMMER23` is more like a season, not a contract.
</blockquote></details>

Changed this to a "realistic" looking contract id

**Pull request merged**
