### PR TITLE
Add missing foreign key indexes

### PR DESCRIPTION
**Pull request by pallost**
Added indexes to all columns that are foreign keys as they are not indexed by default.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123)* status: all files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql` line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123#-NImKwBB8H88HXlDxdt_:-NImKwBB8H88HXlDxdta:b-neyfrh) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e8ca45fb534069120cea114d401c57f3210eee38/migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql#L6)):*
> ```TSQL
> CREATE INDEX idx_vehicle_journey_block ON vehicle_journey.vehicle_journey USING btree (block_id);
> CREATE INDEX idx_vehicle_journey_journey_pattern_ref ON vehicle_journey.vehicle_journey USING btree (journey_pattern_ref_id);
> CREATE INDEX idx_timetabled_passing_time_scheduled_stop_point_in_journey_pattern_ref ON passing_times.timetabled_passing_time	USING btree (scheduled_stop_point_in_journey_pattern_ref_id);
> ```

It looks like there is a tab character in between.
___
*[`migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql` line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123#-NImLXBI3Gc4wvxN53Ir:-NImLXBI3Gc4wvxN53Is:be1xl9a) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e8ca45fb534069120cea114d401c57f3210eee38/migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql#L6)):*
> ```TSQL
> CREATE INDEX idx_vehicle_journey_block ON vehicle_journey.vehicle_journey USING btree (block_id);
> CREATE INDEX idx_vehicle_journey_journey_pattern_ref ON vehicle_journey.vehicle_journey USING btree (journey_pattern_ref_id);
> CREATE INDEX idx_timetabled_passing_time_scheduled_stop_point_in_journey_pattern_ref ON passing_times.timetabled_passing_time	USING btree (scheduled_stop_point_in_journey_pattern_ref_id);
> ```

This index name exceeds the maximum identifier length of 63 characters in PostgreSQL.



_Code quote:_
```TSQL
idx_timetabled_passing_time_scheduled_stop_point_in_journey_pattern_ref
```
___
*[`migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql` line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123#-NImL9CmDWaAT7oXHVOT:-NImL9CmDWaAT7oXHVOU:brhumzt) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e8ca45fb534069120cea114d401c57f3210eee38/migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql#L7)):*
> ```TSQL
> CREATE INDEX idx_vehicle_journey_journey_pattern_ref ON vehicle_journey.vehicle_journey USING btree (journey_pattern_ref_id);
> CREATE INDEX idx_timetabled_passing_time_scheduled_stop_point_in_journey_pattern_ref ON passing_times.timetabled_passing_time	USING btree (scheduled_stop_point_in_journey_pattern_ref_id);
> CREATE INDEX idx_timetabled_passing_time_vehicle_journey ON passing_times.timetabled_passing_time	USING btree (vehicle_journey_id);
> ```

Same here.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123)* status: all files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql` line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123#-NImLXBI3Gc4wvxN53Ir:-NIqVsie3adLw0LZ2qoV:b30f97g) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e8ca45fb534069120cea114d401c57f3210eee38/migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql#L6)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This index name exceeds the maximum identifier length of 63 characters in PostgreSQL.
</blockquote></details>

Because of that the index name is truncated. This may not be the desired end result. Could e.g.  be `idx_timetabled_passing_time_sspijp_ref`.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql` line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123#-NImLXBI3Gc4wvxN53Ir:-NJ44duHEgP6vvaqiUGM:biqyv9y) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/e8ca45fb534069120cea114d401c57f3210eee38/migrations/generic/timetables/1669286958007_add_missing_foreign_key_indexes/up.sql#L6)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Because of that the index name is truncated. This may not be the desired end result. Could e.g.  be `idx_timetabled_passing_time_sspijp_ref`.
</blockquote></details>

good finding!

**Review by jarkkoka — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/123)* status: all files reviewed, 2 unresolved discussions (waiting on @pallost)

**Pull request merged**
