### PR TITLE
Stop point ref by label

### PR DESCRIPTION
**Pull request by jschummer**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73)* status: 0 of 28 files reviewed, 4 unresolved discussions (waiting on @jschummer and @pallost)

___
*[`integration-test/datasets/defaultSetup/scheduled-stop-points.ts` line 140 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2FtBPt8b-IixSIpdpO:-N2FtBPt8b-IixSIpdpP:bi1225g) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1c5032ed343e083c6ec049c9b0087d79282c1ed4/integration-test/datasets/defaultSetup/scheduled-stop-points.ts#L140)):*
> ```XML
> ];
> 
> export const scheduledStopPointInvariants: ScheduledStopPointInvariant[] = uniq(
> ```

I think what you are looking for is _.uniqBy ;)
___
*[`integration-test/datasets/route116/journey-patterns.ts` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2Fto2tAiNwX8QqpCLz:-N2Fto2tAiNwX8QqpCM-:bajgtqi) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1c5032ed343e083c6ec049c9b0087d79282c1ed4/integration-test/datasets/route116/journey-patterns.ts#L33)):*
> ```XML
>   ].map((stopId, index) => ({
>     journey_pattern_id: journeyPatterns[0].journey_pattern_id,
>     scheduled_stop_point_label: scheduledStopPoints.find(
> ```

this is not really readable like this, please save this found label first to a separate variable
___
*[`integration-test/datasets/route116/scheduled-stop-points.ts` line 304 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2Fu1bb1vz9KYJQa2Aw:-N2Fu1bb1vz9KYJQa2Ax:bq5o9bg) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1c5032ed343e083c6ec049c9b0087d79282c1ed4/integration-test/datasets/route116/scheduled-stop-points.ts#L304)):*
> ```XML
> ];
> 
> export const scheduledStopPointInvariants: ScheduledStopPointInvariant[] = uniq(
> ```

_.uniqBy
___
*[`integration-test/datasets/routesAndJourneyPatterns/scheduled-stop-points.ts` line 176 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2FuAeo3qr8OhzhT55D:-N2FuAeo3qr8OhzhT55E:bq5o9bg) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1c5032ed343e083c6ec049c9b0087d79282c1ed4/integration-test/datasets/routesAndJourneyPatterns/scheduled-stop-points.ts#L176)):*
> ```XML
> ];
> 
> export const scheduledStopPointInvariants: ScheduledStopPointInvariant[] = uniq(
> ```

_.uniqBy

**Review by pallost — CHANGES_REQUESTED** [review]
Please update the hasura metadata! Don't forget to add all the non-default relationships as well!

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-:-N2LCJd7E-5SydkDslOq:b-gyl6u1)* status: 0 of 28 files reviewed, 17 unresolved discussions (waiting on @jschummer and @pallost)

___
*[`integration-test/datasets/route116/scheduled-stop-points.ts` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LDcqLAJN7ckh9vMDX:-N2LDcqLAJN7ckh9vMDY:b-uk4bi7) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/integration-test/datasets/route116/scheduled-stop-points.ts#L28)):*
> ```XML
> };
> 
> export const scheduledStopPointWithSameLabelAndOnSameLink: ScheduledStopPoint =
> ```

better name maybe? scheduledStopPointWithSameLabelAndHigherPriorityOnSameLink
___
*[`integration-test/datasets/route116/scheduled-stop-points.ts` line 45 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LEHAS-M0mabn2s5vv:-N2LEHAS-M0mabn2s5vw:bx9aosq) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/integration-test/datasets/route116/scheduled-stop-points.ts#L45)):*
> ```XML
> };
> 
> export const scheduledStopPointWithSameLabelOnLinkAfterNextStop: ScheduledStopPoint =
> ```

better name? scheduledStopPointWithSameLabelOnLinkAfterNextStopWithOverlappingValidityTime
___
*[`integration-test/datasets/route116/scheduled-stop-points.ts` line 59 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LGZ-G2LR2hYexQa_1:-N2LGZ-G2LR2hYexQa_2:b1mxn90) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/integration-test/datasets/route116/scheduled-stop-points.ts#L59)):*
> ```XML
>     scheduled_stop_point_id: '45458d15-eef6-4306-9614-d90ef4528747',
>     validity_start: new Date('2075-05-01 23:11:32Z'),
>     validity_end: new Date('2099-05-01 23:11:32Z'),
> ```

here maybe you could add `priority: 10` to clarify that the priorities are the same, only the validity period differs
___
*[`integration-test/tests/data-integrity/route-journey-pattern-refs/insert-stop-point-with-label-in-use-in-journey-pattern.spec.ts` line 153 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LFpyTAVDuG1Xrtt6H:-N2LFpyTAVDuG1Xrtt6I:b1btagl) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/integration-test/tests/data-integrity/route-journey-pattern-refs/insert-stop-point-with-label-in-use-in-journey-pattern.spec.ts#L153)):*
> ```XML
>     });
> 
>   describe('with the same label and on the same link as another stop', () => {
> ```

"higher priority stop with the same label and on the same link as another stop"
___
*[`integration-test/tests/data-integrity/route-journey-pattern-refs/insert-stop-point-with-label-in-use-in-journey-pattern.spec.ts` line 160 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LG6EM6lSWsq_eXWGI:-N2LG6EM6lSWsq_eXWGJ:b-97y4b6) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/integration-test/tests/data-integrity/route-journey-pattern-refs/insert-stop-point-with-label-in-use-in-journey-pattern.spec.ts#L160)):*
> ```XML
>   });
> 
>   describe('with the same label and on the link previous to the link of another stop', () => {
> ```

"higher priority stop with the same label and to a previous (correct) link"
___
*[`integration-test/tests/data-integrity/route-journey-pattern-refs/insert-stop-point-with-label-in-use-in-journey-pattern.spec.ts` line 167 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LGsB11VdCRMa63ref:-N2LGp_20ex5Mcn6v7y4:bncycz7) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/integration-test/tests/data-integrity/route-journey-pattern-refs/insert-stop-point-with-label-in-use-in-journey-pattern.spec.ts#L167)):*
> ```XML
>   });
> 
>   describe('with the same label and on a link after the link of the next stop with non-overlapping validity time', () => {
> ```

same priority stop with the same label and on a link after the link of the next stop with non-overlapping validity time
___
*[`integration-test/tests/data-integrity/route-journey-pattern-refs/insert-stop-point-with-label-in-use-in-journey-pattern.spec.ts` line 176 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LH2yFAwO5a_Dgg1OE:-N2LH2yFAwO5a_Dgg1OF:b-7bms6f) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/integration-test/tests/data-integrity/route-journey-pattern-refs/insert-stop-point-with-label-in-use-in-journey-pattern.spec.ts#L176)):*
> ```XML
>   });
> 
>   describe('with the same label and on a link after the link of the next stop', () => {
> ```

same priority stop with the same label and on a link after the link of the next stop with over with overlapping validity period
___
*[`migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql` line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LJXu-B5xGMGFWokBw:-N2LJXu-B5xGMGFWokBx:b-4st8sj) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql#L6)):*
> ```TSQL
> BEGIN;
> 
> CREATE TABLE internal_service_pattern.scheduled_stop_point_invariant (
> ```

Are you sure we don't need this table exposed to Hasura? 
___
*[`migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql` line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LKRO-5V8lrbGMelWW:-N2LKRO-5V8lrbGMelWX:bsxk9b5) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql#L6)):*
> ```TSQL
> BEGIN;
> 
> CREATE TABLE internal_service_pattern.scheduled_stop_point_invariant (
> ```

short comment here would be welcome:
"create table for scheduled stop point invariants and fill it up with the distinct stop labels"
___
*[`migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LKfNFErSOkiLoJPMY:-N2LKfNFErSOkiLoJPMZ:be16izc) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql#L25)):*
> ```TSQL
> BEGIN;
> 
> ALTER TABLE journey_pattern.scheduled_stop_point_in_journey_pattern
> ```

short comment here would be welcome:
"add label column to ssp-in-jp table and fill it up with the referenced stops' labels"
___
*[`migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LKDS2CKJDtZ8nWz08:-N2LKDS2CKJDtZ8nWz09:bbyx1or) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql#L28)):*
> ```TSQL
>   ADD COLUMN scheduled_stop_point_label TEXT REFERENCES internal_service_pattern.scheduled_stop_point_invariant (label);
> 
> CREATE INDEX scheduled_stop_point_in_journey__scheduled_stop_point_label_idx
> ```

scheduled_stop_point_in_journey_pattern_scheduled_stop_point_label_idx
___
*[`migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql` line 43 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LKuLm-TKUYCrndDG7:-N2LKuLm-TKUYCrndDG8:b-vzd856) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql#L43)):*
> ```TSQL
> BEGIN;
> 
> ALTER TABLE journey_pattern.scheduled_stop_point_in_journey_pattern
> ```

short comment could be added:
"remove the stop id column as the label is used as foreign key from now on"
___
*[`migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LJCqyEey7TZ3UqS43:-N2LJCqyEey7TZ3UqS44:b-clvf75) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql#L10)):*
> ```TSQL
> 
> 
> CREATE FUNCTION journey_pattern.verify_route_journey_pattern_refs(
> ```

could you please a short comment here that what changed compared to the previous version of this function? I don't have the brainpower now to go through the whole function logic...

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73)* status: 0 of 28 files reviewed, 18 unresolved discussions (waiting on @jschummer and @pallost)

___
*[`migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql` line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LNVjS1mq-rd6iHa5t:-N2LNVjS1mq-rd6iHa5u:b-ica1op) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql#L33)):*
> ```TSQL
> UPDATE journey_pattern.scheduled_stop_point_in_journey_pattern sspijp
>   SET scheduled_stop_point_label = (
>     SELECT "label"
> ```

I suspect that changing the foreign key from id to label should definitely affect the generated hasura metadata. Please make sure that the metadata is updated and all the relationships are defined between entities back and forth

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73)* status: 0 of 30 files reviewed, 5 unresolved discussions (waiting on @jschummer and @pallost)

___
*[`integration-test/datasets/route116/scheduled-stop-points.ts` line 59 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LGZ-G2LR2hYexQa_1:-N2kNZ9J1tBIdvQpFGb8:bu7cg86) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/integration-test/datasets/route116/scheduled-stop-points.ts#L59)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

If the priority would be 10, then this test might fail because of another constraint. (Shouldn't fail, if that other constraint is working properly, but just for the theory.)

I think it works better if the priority of the same as in `scheduledStopPointWithSameLabelOnLinkAfterNextStop`, because the test insert is supposed to fail for that and for this one (with the only difference being the different validity time), the test insert is supposed to work fine.
</blockquote></details>

oh, didn't notice that you used scheduledStopPointWithSameLabelOnLinkAfterNextStop here as a base, so it does have priority 20
___
*[`migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LJCqyEey7TZ3UqS43:-N2kNv8bAEP1-r-7MaP5:bd5l6mr) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql#L10)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Yes, good point. I did update the comments in the function itself, but added a new comment summarizing the changes that were made.
</blockquote></details>

thanks!

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 19 of 28 files at r1, 2 of 2 files at r2, 8 of 9 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73)* status: 30 of 31 files reviewed, 7 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[`-- commits` line 11 at r5](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N3TWWK3CetTYW0Prdmy):*
typo => "indirectly"



_Code quote:_
```
indirectily
```
___
*[`migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql` line 31 at r5](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N3TfYPM1wo2nY7ZUH-6:-N3TfYPM1wo2nY7ZUH-7:bvs3t04) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bdc66a23009cea910af3805bc892634ffd0389d/migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql#L31)):*
> ```TSQL
>   -- This implicitly ensures
>   --   - that every stop point in the journey pattern resides on a link that is part of the journey pattern's route
>   --   - the stop points' order is the same as the order of the links they reside on
> ```

The query verifying these assertions is very complicated. Because of that it is not easily understood. However, when tests are good, then it serves its purpose even though most developers in the team may never fully understand the logic in recursive query.

I think this function could be improved as follows:
- The different assertions listed below should be done in separate steps. There should be a separate error message for each of these assertions. In the error message, the stop-in-journey-pattern IDs or stop labels should be listed that are violating the constraint.
- Comparison between route links and journey pattern stops (or their links associated) could be done using PostgreSQL array operators/functions. By aggregating all route links and all links referenced by journey pattern stops to two separate arrays (one for route, another derived from journey pattern), the logic could be done in a more understandable way than using a recursive query. Using array logic, the query could be more easily split into multiple ones.



_Code quote:_
```TSQL
  --   - that every stop point in the journey pattern resides on a link that is part of the journey pattern's route
  --   - the stop points' order is the same as the order of the links they reside on
  --   - the stop points' directions match the directions, in which the stop points' links are visited.
```

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73)* status: 30 of 31 files reviewed, 7 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[`migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql` line 31 at r5](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N3TfYPM1wo2nY7ZUH-6:-N3Ti2FC78mgdOeNEyf6:b-edfzyr) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bdc66a23009cea910af3805bc892634ffd0389d/migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql#L31)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The query verifying these assertions is very complicated. Because of that it is not easily understood. However, when tests are good, then it serves its purpose even though most developers in the team may never fully understand the logic in recursive query.

I think this function could be improved as follows:
- The different assertions listed below should be done in separate steps. There should be a separate error message for each of these assertions. In the error message, the stop-in-journey-pattern IDs or stop labels should be listed that are violating the constraint.
- Comparison between route links and journey pattern stops (or their links associated) could be done using PostgreSQL array operators/functions. By aggregating all route links and all links referenced by journey pattern stops to two separate arrays (one for route, another derived from journey pattern), the logic could be done in a more understandable way than using a recursive query. Using array logic, the query could be more easily split into multiple ones.
</blockquote></details>

As follow-up to my previous comment: the suggested improvements are not meant to be done in this PR (may be done in the future).

Because of there are so many ways in which the constraint could be violated, it would really be helpful if the error message was giving hints what parts of the journey pattern are not matching the route.

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73)* status: 27 of 34 files reviewed, 6 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`integration-test/datasets/route116/scheduled-stop-points.ts` line 59 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LGZ-G2LR2hYexQa_1:-N3rpiI0A7-Bj2MRHNOU:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/integration-test/datasets/route116/scheduled-stop-points.ts#L59)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

oh, didn't notice that you used scheduledStopPointWithSameLabelOnLinkAfterNextStop here as a base, so it does have priority 20
</blockquote></details>

Done.
___
*[`migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql` line 28 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LKDS2CKJDtZ8nWz08:-N3rpjjPEDR5bJBqUEZQ:bsjdtt6) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql#L28)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

umm, I meant that the `journey__` part is probably a typo and you meant to write `journey_pattern_` instead...?
</blockquote></details>

That was part of the generated constraint name, which was in use before (scheduled stop point _id_-based then). I suspect the name was shortened previously, that's why the two underscores got in there. If it's ok, I'd rather leave it this way.
___
*[`migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql` line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LNVjS1mq-rd6iHa5t:-N3rr2mA3EFuEsDIlVqR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768620000_scheduled_stop_point_label/up.sql#L33)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

thanks 
</blockquote></details>

Done.
___
*[`migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql` line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N2LJCqyEey7TZ3UqS43:-N3rq3F_0Du7Wef4Cz4m:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3a49f9433cef8b197faec26af318e67e859aca38/migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

thanks!
</blockquote></details>

Done.
___
*[`migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql` line 31 at r5](https://reviewable.io/reviews/hsldevcom/jore4-hasura/73#-N3TfYPM1wo2nY7ZUH-6:-N3rq5xC5L7Oza5ZFg_Z:bqxgzlo) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bdc66a23009cea910af3805bc892634ffd0389d/migrations/generic/default/1652768651000_scheduled_stop_point_label_constraint_update/up.sql#L31)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

As follow-up to my previous comment: the suggested improvements are not meant to be done in this PR (may be done in the future).

Because of there are so many ways in which the constraint could be violated, it would really be helpful if the error message was giving hints what parts of the journey pattern are not matching the route.
</blockquote></details>

I know it looks like there are many reasons for the check to fail, but there actually are only 2:

1. Not all stop points can be reached when traversing the route's links (`infra_link_seq.infrastructure_link_sequence IS NULL`)
2. Not all stop points can be reached in the same order for all stop point instances when traversing the route's links (`infra_link_seq.stop_point_order != infra_link_seq.infra_link_order`)

All other conditions seen in the statements are only used to "simulate" the proper route traversal.

Maybe we can think about some refactoring of this in the future.

**Pull request merged**
