### PR TITLE
Add `timing_place_id` parameter to the function used to insert stop points

### PR DESCRIPTION
**Pull request by jarkkoka**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/164)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/164)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @culka, @jarkkoka, and @Leitsi)

___
*[`test/hasura/generic/networkdb/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 64 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/164#-NRHlQkH0VyuqfhTbwP1:-NRHlQkH0VyuqfhTbwP2:b-k9rv7q) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/8674b25423bb3db276932d88f3e2edb13e2e2089/test/hasura/generic/networkdb/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L64)):*
> ```XML
>     includeTimingPlaceId = true,
>   ) => {
>     const mandatoryParams = `
> ```

doing this with string building is not a very nice solution, let's rather use arrays:

```
const params = [
  `'${scheduledStopPoint.scheduled_stop_point_id}'::uuid`,
  `'${asEwkb(
        scheduledStopPoint.measured_location,
      )}'::geography(PointZ, 4326)`,
  ...
];

if (includeTimingPlaceId) {
  params.push(`'${scheduledStopPoint.timing_place_id}'::uuid`);
}

...
db.singleQuery(dbConnection, `SELECT internal_service_pattern.insert_scheduled_stop_point_with_vehicle_mode(${params.join(',')})`)
```

even better would be to actually include serialization here (e.g. UUID-typed fields as serialized as `'...':uuid`), but that's not in scope of this PR

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/164)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @culka, @jarkkoka, and @Leitsi)

___
*[`test/hasura/generic/networkdb/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 64 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/164#-NRHlQkH0VyuqfhTbwP1:-NRHnSeGA1fhkdRD8YYy:b-vs06qv) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/8674b25423bb3db276932d88f3e2edb13e2e2089/test/hasura/generic/networkdb/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L64)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

doing this with string building is not a very nice solution, let's rather use arrays:

```
const params = [
  `'${scheduledStopPoint.scheduled_stop_point_id}'::uuid`,
  `'${asEwkb(
        scheduledStopPoint.measured_location,
      )}'::geography(PointZ, 4326)`,
  ...
];

if (includeTimingPlaceId) {
  params.push(`'${scheduledStopPoint.timing_place_id}'::uuid`);
}

...
db.singleQuery(dbConnection, `SELECT internal_service_pattern.insert_scheduled_stop_point_with_vehicle_mode(${params.join(',')})`)
```

even better would be to actually include serialization here (e.g. UUID-typed fields as serialized as `'...':uuid`), but that's not in scope of this PR
</blockquote></details>

actually, you might be able to reuse the `serializeInputValue()` function

**Review by pallost — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/164#-:-NRHprcH3YKPf2-jGOev:bnfp4nl)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @culka, @jarkkoka, and @Leitsi)

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/164)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @culka, @Leitsi, and @pallost)

___
*[`test/hasura/generic/networkdb/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts` line 64 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/164#-NRHlQkH0VyuqfhTbwP1:-NRHxZNB5zgcJp8BjoiZ:b3o4ra6) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/8674b25423bb3db276932d88f3e2edb13e2e2089/test/hasura/generic/networkdb/unit-tests/function-insert_scheduled_stop_point_with_vehicle_mode/insert-scheduled-stop-point.spec.ts#L64)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

actually, you might be able to reuse the `serializeInputValue()` function
</blockquote></details>

Ok. Thanks for the comments. Will change to use arrays instead of string concatenation.

Yes, I agree that serializing `'...':uuid` could be done in a separate PR.

**Pull request merged**
