### PR TITLE
Project template

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1)* status: 0 of 22 files reviewed, 4 unresolved discussions (waiting on @tk-vincit)

___
*[default.conf, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4_f6Z-1aUctSeLCgE:-M_4_f6_9LAGitqUL38m:b-kq03ax) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/default.conf#L1)):*
> ```
> server {
> ```

you should move this file to a folder named e.g. `nginx` to clarify that it has nothing to do with hasura
___
*[docker-compose.yml, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4a0sq5NYt9GvKp94F:-M_4a0sq5NYt9GvKp94G:b-xbe2ck) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/docker-compose.yml#L21)):*
> ```YAML
> 
>   hasura:
>     image: "hasura/graphql-engine:v1.3.3.cli-migrations-v2"
> ```

you have already built a Dockerfile to extend the existing hasura image. Let's use that here in docker-compose:
- remove the `image:` attribute
- remove the `volume:` attribute
- remove the `HASURA_GRAPHQL_UNAUTHORIZED_ROLE` environment variable
...as they are already defined in your Dockerfile above
- add the `build: .` attribute to instruct docker-compose to use that image instead
- the `docker-compose up --build` command that you use below will make sure that if migrations or metadata changes, then when restarting the cluster, it'll update itself
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4cbPe0rKm-1SY6fZt:-M_4cbPf2K7PMzNeytDD:b-tznewz) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/README.md#L32)):*
> ```Markdown
> 1. Run `hasura console` to start the console.
> 1. Run `hasura migrate ...` to read or write DB migration files.
> 1. Run `hasura metadata ...` to read or write Hasura configuration.
> ```

Would be awesome if you added a section also on how to use the docker image. You could probably just copy 99% of the text from here: https://registry.hub.docker.com/r/hasura/graphql-engine
___
*[.github/workflows/cd.yml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4dRsqAIT4l0Eg7BC_:-M_4dRsqAIT4l0Eg7BCa:bwqvpjn) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/.github/workflows/cd.yml#L20)):*
> ```YAML
> 
>       - name: Extract branch name to env variable # https://github.community/t/run-step-on-if-branch-tag-is/16965/5
>         run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
> ```

I suggest you using the following action instead for retrieving the branch name more reliably: `rlespinasse/github-slug-action@v3.x`

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1)* status: 0 of 22 files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[docker-compose.yml, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4a0sq5NYt9GvKp94F:-M_4kKq43uySUDi-ho_r:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/docker-compose.yml#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you have already built a Dockerfile to extend the existing hasura image. Let's use that here in docker-compose:
- remove the `image:` attribute
- remove the `volume:` attribute
- remove the `HASURA_GRAPHQL_UNAUTHORIZED_ROLE` environment variable
...as they are already defined in your Dockerfile above
- add the `build: .` attribute to instruct docker-compose to use that image instead
- the `docker-compose up --build` command that you use below will make sure that if migrations or metadata changes, then when restarting the cluster, it'll update itself
</blockquote></details>

Done.
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4cbPe0rKm-1SY6fZt:-M_5937YA-3cI8objF_2:bpk4nqt) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/README.md#L32)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Would be awesome if you added a section also on how to use the docker image. You could probably just copy 99% of the text from here: https://registry.hub.docker.com/r/hasura/graphql-engine
</blockquote></details>

What kind of readme do you want? How about now?
___
*[.github/workflows/cd.yml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4dRsqAIT4l0Eg7BC_:-M_58gjn5iu35mKhd2Bo:ba5k94l) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/.github/workflows/cd.yml#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I suggest you using the following action instead for retrieving the branch name more reliably: `rlespinasse/github-slug-action@v3.x`
</blockquote></details>

Do we want to use 3rd party action for that? Anyway, refactored this to use action that you mentioned.
___
*[default.conf, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4_f6Z-1aUctSeLCgE:-M_4edk0-7wm3JpyY9Zv:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/default.conf#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should move this file to a folder named e.g. `nginx` to clarify that it has nothing to do with hasura
</blockquote></details>

Done.

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 18 of 22 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1)* status: all files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[.github/workflows/cd.yml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4dRsqAIT4l0Eg7BC_:-M_5SSlj64jDXbYT70rT:b-cajftl) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/.github/workflows/cd.yml#L20)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we want to use 3rd party action for that? Anyway, refactored this to use action that you mentioned.
</blockquote></details>

(and if we want to be really paranoid we should refer to the commit SHA instead of the tag, as they're harder to forge)

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1)* status: all files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[Dockerfile, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_Kq9Ws7mFHoiqJQ2X6:-M_Kq9Ws7mFHoiqJQ2X7:b-ah4doc) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0a2eef800186cff547a9cad55abb380899e6d8c7/Dockerfile#L1)):*
> ```Dockerfile
> FROM hasura/graphql-engine:v1.3.3.cli-migrations-v2
> ```

why not using the cli-migrations-v3 version?

**Review by haphut — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1)* status: all files reviewed, 6 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[Dockerfile, line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_Kq9Ws7mFHoiqJQ2X6:-M_KuqXYAQYQVd9SG2id:baakqmy) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0a2eef800186cff547a9cad55abb380899e6d8c7/Dockerfile#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

why not using the cli-migrations-v3 version?
</blockquote></details>

I think v3 of cli migration format came with hasura v2. The current file structure is according to cli migration format v2.
___
*[docker-compose.yml, line 44 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_Kv2AY2nB6FQ6KXWSG:-M_Kv2AY2nB6FQ6KXWSH:b-ol1pyl) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0a2eef800186cff547a9cad55abb380899e6d8c7/docker-compose.yml#L44)):*
> ```YAML
>       retries: 3
> 
>   proxy:
> ```

Why do we need the proxy service? Can we just expose Hasura port 8080 from 80?

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1)* status: all files reviewed, 6 unresolved discussions (waiting on @haphut and @pallost)

___
*[docker-compose.yml, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4a0sq5NYt9GvKp94F:-M_L6E0wD0jRSFbdhuEy:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/docker-compose.yml#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[docker-compose.yml, line 5 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_KRAZBACHlDz_lN63x:-M_L6HntB1rXykTIxsrv:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0a2eef800186cff547a9cad55abb380899e6d8c7/docker-compose.yml#L5)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Maybe use `postgis/postgis:12-3.0-alpine` to match the current Azure extensions more closely: https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions .

Unfortunately we need to keep updating this when Azure changes its extension versions. We have no monitoring for Azure extension versions and we will probably not get the exact same versions this way either.
</blockquote></details>

Done
___
*[docker-compose.yml, line 44 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_Kv2AY2nB6FQ6KXWSG:-M_L6Jlj04LxSFg0Pl0s:bmjltlm) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0a2eef800186cff547a9cad55abb380899e6d8c7/docker-compose.yml#L44)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Why do we need the proxy service? Can we just expose Hasura port 8080 from 80?
</blockquote></details>

I think this is forgotten from graphql playground repository, where this was needed for hosting frontend.
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_4cbPe0rKm-1SY6fZt:-M_L6Xva2Ots7DocMg9A:b9tcumi) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1ea8fe376f5c1fb7048479bae049ed5ce53bdd7a/README.md#L32)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

How about using the jore4-sql-schema-experiment README instead of the jore4-graphql-playground README as a template? The first one has a more detailed README for our use.
</blockquote></details>

Good idea. Copied relevant parts from it here. Better now?
___
*[.github/workflows/cd.yml, line 18 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/1#-M_KSL7zARyrM6wfwvIm:-M_L6abu6ccJXbQJ0A6S:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0a2eef800186cff547a9cad55abb380899e6d8c7/.github/workflows/cd.yml#L18)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Remove extra newline.
</blockquote></details>

Done

**Comment by tk-vincit** [comment]
No functional changes, just small re-organizing commits. Will merge this now as two reviewers have approved.

**Pull request merged**
