### PR TITLE
Feat/validity period and priority

### PR DESCRIPTION
**Pull request by jschummer**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @jschummer and @pallost)

___
*[integration-test/tests/mutations/scheduled-stop-point/update.spec.ts, line 113 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDA0iREETDcB-NptOQ:-MoDA0iREETDcB-NptOR:bslhv7g) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/scheduled-stop-point/update.spec.ts#L113)):*
> ```XML
>           ssp.direction,
>           ssp.measured_location,
>           ssp.label,
> ```

you should probably include also the validity_start and validity_end fields to the tests

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 16 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27)* status: 16 of 17 files reviewed, 11 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[integration-test/datasets/types.ts, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDn61SA48if3pHZ7KC:-MoDn61T19qghRUaWAgD:b-x2ppxb) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/datasets/types.ts#L18)):*
> ```
> ScheduledStopPoint
> ```

Should validity period be included in this type?
___
*[integration-test/datasets/types.ts, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnENf8l_2fcTDnOK3:-MoDnENf8l_2fcTDnOK4:b-5v3tx9) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/datasets/types.ts#L27)):*
> ```
> Route
> ```

Should validity period be included in this type?
___
*[integration-test/tests/mutations/route/insert.spec.ts, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnx1jEZFDpM0L_Cpz:-MoDnx1jEZFDpM0L_Cq-:b-mrnzuy) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/route/insert.spec.ts#L28)):*
> ```
> priority
> ```

What about adding validity period start and end time? Do you intend to increase test coverage in a later PR?
___
*[integration-test/tests/mutations/route/insert.spec.ts, line 104 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnueK3_9nNIY6q6bV:-MoDnueK3_9nNIY6q6bW:b-6oss5d) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/route/insert.spec.ts#L104)):*
> ```
> r.priority
> ```

Maybe should test that validity period fields are also returned on request.
___
*[integration-test/tests/mutations/route/update.spec.ts, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDns0D6sUwCG-LTblv:-MoDns0E2_vmS2BYZXON:bfl8z7f) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/route/update.spec.ts#L36)):*
> ```
> priority
> ```

Maybe should test that validity period fields are also returned on request.
___
*[integration-test/tests/mutations/route/update.spec.ts, line 102 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnq543JDJafpP0XUT:-MoDnq543JDJafpP0XUU:b-6oss5d) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/route/update.spec.ts#L102)):*
> ```
> r.priority
> ```

Maybe should test that validity period fields are also returned on request.
___
*[integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnjGeEItxwnXM-_HW:-MoDnjGeEItxwnXM-_HX:bfl8z7w) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts#L21)):*
> ```
> priority
> ```

Maybe should test that validity period fields are also returned on request?
___
*[integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts, line 86 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnlwD1ctaWhpAM9rJ:-MoDnlwD1ctaWhpAM9rK:b-b6ic5u) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts#L86)):*
> ```
> ssp.priority
> ```

Maybe should test that validity period fields are also returned on request?
___
*[integration-test/tests/mutations/scheduled-stop-point/insert.spec.ts, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnWYWCvK8p3w3w_Gd:-MoDnWYWCvK8p3w3w_Ge:b-rmjh2r) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/scheduled-stop-point/insert.spec.ts#L38)):*
> ```XML
>         measured_location,
>         label,
>         priority
> ```

Maybe should test that validity period fields are also returned.
___
*[integration-test/tests/mutations/scheduled-stop-point/insert.spec.ts, line 113 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnftz1pWQM5wrkVQv:-MoDnftz1pWQM5wrkVQw:b-dkecjz) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/scheduled-stop-point/insert.spec.ts#L113)):*
> ```
> ssp.priority
> ```

Maybe should test that validity period fields are also returned.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27)* status: 16 of 17 files reviewed, 12 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[integration-test/tests/mutations/scheduled-stop-point/insert.spec.ts, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnWYWCvK8p3w3w_Gd:-MoDoddt2AD16KCEpp0v:b-t77xc3) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/integration-test/tests/mutations/scheduled-stop-point/insert.spec.ts#L38)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Maybe should test that validity period fields are also returned.
</blockquote></details>

agreed
___
*[migrations/default/1636382626164_validity_periods_and_priorities/up.sql, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnzjg2ytiKDVW6VGI:-MoDnzjg2ytiKDVW6VGJ:b-abs33v) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/migrations/default/1636382626164_validity_periods_and_priorities/up.sql#L6)):*
> ```TSQL
> 
> ALTER TABLE internal_service_pattern.scheduled_stop_point
> ADD COLUMN validity_start TIMESTAMP WITH TIME ZONE,
> ```

I'd make these validity columns NOT NULLable (so essentially required fields). If the stop has always been valid, let's just set it to 1970. If always we bee valid, let's set it to e.g. 2100. But it would simplify validity constraint checks a LOT and also simplify the UI to just make these fields always required. What is @ossiberg 's opinion on this..?

**Review by jschummer — COMMENTED** [review]
I was not 100% convinced it's strictly needed to include validity and priority columns in the tests, so I didn't first add them. But it probably is good to check the INSTEAD OF -triggers work with those too, so I added those now (together with the necessary conversion functionality to be able to exchange and compare timestamps correctly between JS / GraphQL / SQL...)

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-:-MoJ6N4t6G8HtxL9rTTZ:b-u0ec0y)* status: 7 of 19 files reviewed, 12 unresolved discussions (waiting on @jarkkoka, @jschummer, @ossiberg, and @pallost)

___
*[migrations/default/1636382626164_validity_periods_and_priorities/up.sql, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnzjg2ytiKDVW6VGI:-MoJ5LaD67PdPku8wmJG:b-sa5g3j) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/migrations/default/1636382626164_validity_periods_and_priorities/up.sql#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd make these validity columns NOT NULLable (so essentially required fields). If the stop has always been valid, let's just set it to 1970. If always we bee valid, let's set it to e.g. 2100. But it would simplify validity constraint checks a LOT and also simplify the UI to just make these fields always required. What is @ossiberg 's opinion on this..?
</blockquote></details>

I think on the data model level we can have NULL mean "has always been valid" / "does not expire". In the constraints, this will just translate to adding a "OR somerow.validity_start IS NULL" or similar condition, as far as I can see now.

If we want to restrict input, we need to have support for that in the UI anyway, since the UI needs to have own validation or needs to be able to interpret the server response in case of a conflict.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27)* status: 7 of 19 files reviewed, 14 unresolved discussions (waiting on @jarkkoka, @jschummer, @ossiberg, and @pallost)

___
*[integration-test/datasets/scheduled-stop-points.ts, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoJ7TWu-GJnm4tV2XaZ:-MoJ7TWu-GJnm4tV2Xa_:bv5fg1m) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/652e276934359f21893059f9d0107d02e3b949cc/integration-test/datasets/scheduled-stop-points.ts#L20)):*
> ```XML
>     label: "stop1",
>     priority: 10,
>     validity_start: new Date("2065-02-01 12:34:56"),
> ```

I wonder was it intentional that the validity start is after the end date
___
*[integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts, line 88 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoJ8vVS1NyMz9Y9nhdL:-MoJ8vVS1NyMz9Y9nhdM:b-5jxso1) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/652e276934359f21893059f9d0107d02e3b949cc/integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts#L88)):*
> ```XML
> 
>     expect(response.rows).toEqual(
>       expect.arrayContaining(
> ```

I just noticed the logic error in this unit test: `expect.arrayContaining` means that we expect that AT LEAST the given rows should be present in the result. It does not test however whether the actual row that you targeted was deleted.

I don't actually really see the point of you `expect.arrayContaining` anywhere... if you want to compare the exact content of these arrays, you should just use `expect(response.rows).toEqual([...result rows here])`
___
*[migrations/default/1636382626164_validity_periods_and_priorities/up.sql, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoDnzjg2ytiKDVW6VGI:-MoJ8QCc7plXiG-yUAE_:b-16lbko) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/45ed8f448e416eda6df011c1a3f03f48131abea5/migrations/default/1636382626164_validity_periods_and_priorities/up.sql#L6)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I think on the data model level we can have NULL mean "has always been valid" / "does not expire". In the constraints, this will just translate to adding a "OR somerow.validity_start IS NULL" or similar condition, as far as I can see now.

If we want to restrict input, we need to have support for that in the UI anyway, since the UI needs to have own validation or needs to be able to interpret the server response in case of a conflict.
</blockquote></details>

I disagree that the UI should do the validation, but I do understand the need for allowing NULL values. Let's leave it like this then :+1:

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27)* status: 7 of 19 files reviewed, 14 unresolved discussions (waiting on @jarkkoka, @jschummer, @ossiberg, and @pallost)

___
*[integration-test/datasets/scheduled-stop-points.ts, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoJ7TWu-GJnm4tV2XaZ:-MoJDkLV0ryR8f5w-ZPB:b-gtk4ms) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/652e276934359f21893059f9d0107d02e3b949cc/integration-test/datasets/scheduled-stop-points.ts#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I wonder was it intentional that the validity start is after the end date
</blockquote></details>

Nope, but I don't mind there being a case which the constraints can catch right away :-) 
___
*[integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts, line 88 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoJ8vVS1NyMz9Y9nhdL:-MoJDr1JEISr6vY7Fwmt:bb55sv9) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/652e276934359f21893059f9d0107d02e3b949cc/integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts#L88)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I just noticed the logic error in this unit test: `expect.arrayContaining` means that we expect that AT LEAST the given rows should be present in the result. It does not test however whether the actual row that you targeted was deleted.

I don't actually really see the point of you `expect.arrayContaining` anywhere... if you want to compare the exact content of these arrays, you should just use `expect(response.rows).toEqual([...result rows here])`
</blockquote></details>

This was just used as a way to do an order-independent array content comparison. That's why the rowCount also has to be compared.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27)* status: 7 of 19 files reviewed, 12 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts, line 88 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/27#-MoJ8vVS1NyMz9Y9nhdL:-MoJEUX8BmFetACT3V3H:b-54s4ia) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/652e276934359f21893059f9d0107d02e3b949cc/integration-test/tests/mutations/scheduled-stop-point/delete.spec.ts#L88)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

This was just used as a way to do an order-independent array content comparison. That's why the rowCount also has to be compared.
</blockquote></details>

yeah, good enough for me :+1:

**Pull request merged**
