### PR TITLE
Update repository documentation

### PR DESCRIPTION
**Pull request by pallost**
- added Table of Contents to ease navigation between sections
- rearranged sections to make more sense
- did some minor fixes to the existing instructions
- added some sections on how the migrations are structured and instructions on how they should be developed

Closes https://github.com/HSLdevcom/jore4/issues/1052

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160)* status: all files reviewed, 9 unresolved discussions (waiting on @pallost)

___
*[`README.md` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQeZ1si-0EVWm6U50-l:-NQeZ1si-0EVWm6U50-m:b-iweegs) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L6)):*
> ```Markdown
> 
> 
> 
> ```

I don't see any mentions on how to update this with doctoc. I guess you did this locally? Could maybe add as dev npm package and add yarn command + document here how to update?
___
*[`README.md` line 50 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQeZdEQDszNN5k0rmkt:-NQeZdEQDszNN5k0rmku:undefined) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L50)):*
> ```Markdown
> Other possibly relevant commands for Hasura CLI:
> 
> 1. Run `hasura migrate ...` to read or write DB migration files. Note that this runs the migrations from your local workspace, not the docker image. Should make sure that's Hasura's `config.yaml` points to the correct migrations folder that is intended to be used.
> ```





_Suggestion:_
```Markdown
Should make sure that Hasura's `config.yaml`
```
___
*[`README.md` line 83 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQe_OBZ8VUySn8zhis8:-NQe_OBZ8VUySn8zhis9:b45h) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L83)):*
> ```Markdown
> #### Developing migrations
> 
> The JORE4 project had been using the "classic" migrations that create objects in the up migration and roll back the changes in the down migration. With the data model getting more and more complex, maintainability has taken a massive hit. PostgreSQL stores the SQL functions bodies as plain text, meaning the if a table or column has changed, ALL the functions, views, etc. had to be dropped and recreated to get updated. Both for up and the down migrations. This has taken a big toll on maintainability as complex SQL functions had to be reviewed again and again from a clean slate, not seeing that the actual change was e.g. just a renamed column as proper diffing was not possible.
> ```





_Suggestion:_
```Markdown
meaning that if
```
___
*[`README.md` line 83 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQe_fnLCa7YHaKPv08n:-NQe_fnLCa7YHaKPv08o:ba6emn2) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L83)):*
> ```Markdown
> #### Developing migrations
> 
> The JORE4 project had been using the "classic" migrations that create objects in the up migration and roll back the changes in the down migration. With the data model getting more and more complex, maintainability has taken a massive hit. PostgreSQL stores the SQL functions bodies as plain text, meaning the if a table or column has changed, ALL the functions, views, etc. had to be dropped and recreated to get updated. Both for up and the down migrations. This has taken a big toll on maintainability as complex SQL functions had to be reviewed again and again from a clean slate, not seeing that the actual change was e.g. just a renamed column as proper diffing was not possible.
> ```

Most of the readme is split in sensible line lengths. Could split this to smaller chunks as well. Slightly better for source control.
___
*[`README.md` line 93 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQe_wlUEAhzZVNtgTQw:-NQe_wlUEAhzZVNtgTQx:bohmhw4) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L93)):*
> ```Markdown
> _Repeatable migrations_:
> 
> In contraty of the data migrations, repeatable migrations are repeated, meaning that each time the Hasura container is restarted, these migrations are executed again and again. These migrations contain the text `_R_` in their names. We achieve this by hacking into Hasura's migration status table and making it believe that these migrations haven't been applied yet. Note that this also allows that the repeatable migrations are applied in the same order (so technically in the order of the timestamps). We aim to only do changes that are idempotent and won't change the data (e.g. creating functions and views).
> ```

Same here, split to smaller rows?
___
*[`README.md` line 93 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQebzgT4It4SwHULEy1:-NQebzgT4It4SwHULEy2:undefined) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L93)):*
> ```Markdown
> _Repeatable migrations_:
> 
> In contraty of the data migrations, repeatable migrations are repeated, meaning that each time the Hasura container is restarted, these migrations are executed again and again. These migrations contain the text `_R_` in their names. We achieve this by hacking into Hasura's migration status table and making it believe that these migrations haven't been applied yet. Note that this also allows that the repeatable migrations are applied in the same order (so technically in the order of the timestamps). We aim to only do changes that are idempotent and won't change the data (e.g. creating functions and views).
> ```





_Suggestion:_
```Markdown
In contrary to the data migrations
```
___
*[`README.md` line 115 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQecEqoCrzrMfi1YwKD:-NQecEqoCrzrMfi1YwKE:undefined) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L115)):*
> ```Markdown
> A: Create them as _data migration_ scripts. Indexes cannot be freely dropped and recreated as e.g. functions would be as they are tightly coupled with the underlying tables.
> 
> Q: How to add check contraints to tables?
> ```





_Suggestion:_
```Markdown
Q: How to add check constraints to tables?
```
___
*[`README.md` line 136 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQeb-ZpBeBVRTvz82eK:-NQeb-ZpBeBVRTvz82eL:bnet6oh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L136)):*
> ```Markdown
> On the other hand, the admin UI exposes all the choices.
> 
> Start the admin UI.
> ```

I think `:` was just fine here.
___
*[`README.md` line 153 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQeb76v5tUoxTwbZcjr:-NQeb76v5tUoxTwbZcjs:undefined) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L153)):*
> ```Markdown
> When you make changes in the admin UI, `hasura console` will modify `metadata/*.yaml` files accordingly in the background.
> 
> Note: if you modify the metadata within the docker container (http://localhost:3201), the yamls files are not refreshed. Do make sure you make the changes using `hasura console`.
> ```





_Suggestion:_
```Markdown
the yaml files 
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160)* status: 0 of 1 files reviewed, 19 unresolved discussions (waiting on @Leitsi and @tk-vincit)

___
*[`README.md` line 167 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQicI_E614LzGerEuSl:-NQjXcEt3WWxqlzo2W2m:b-5o886r) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L167)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Don't we do exactly that with test-db-manager when seeding test data with hardcoded id values..?
</blockquote></details>

yeah, this is a bit misleading. This advice is correct if we had numeric IDs that were generated internally by a sequence. For UUIDs, it's not necessary as we can generate a unique ID externally. (I didn't write this :P)
___
*[`README.md` line 171 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQidAjg1sX58yg48fHN:-NQjYLWf72vN_jV-UVaA:b4gy4s1) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L171)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Btw, is this the reason we haven't used those?
</blockquote></details>

yes. But also I'm not sure if Hasura can handle enum data types either
___
*[`README.md` line 192 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQieOYRDeSOPr6Gl93i:-NQjcqhx33tBAghgLjKK:b-o6nk5y) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L192)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This was the first time different build target was mentioned.
Should we also have a brief chapter about those, which would document at least allowed values and explain when each of those is needed?
</blockquote></details>

I don't have the energy to bring it to the scope of this PR. Let's create a separate ticket about this...
___
*[`README.md` line 193 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQidbuw5JgtlK4pc1NS:-NQjcm2E7ua7W5PLyk7H:bh9aar2) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L193)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This could be explained with a bit more detail, so that this would be easier to do even for newcomers or users with less docker experience.

Should we add stop-dependencies script (similar as in UI repository) for this? And maybe even restart-dependencies.sh, which would practically call `./stop-dependencies.sh && ./start-dependencies.sh`
</blockquote></details>

I added a stop-dependencies script as well
___
*[`README.md` line 230 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQifREH13bj-yTyUxRw:-NQjdn_g2xhniJlegCaV:b-8qz3xs) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L230)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

this a) a) a) doesn't seem to work as 1. 1. 1. works. :) So maybe just a) b) c) etc. Maybe also add newlines, now this is rendered on single line in github ui.
See how this is rendered in https://github.com/HSLdevcom/jore4-hasura/tree/update-documentation
</blockquote></details>

weeeeird... good catch, fixed it.
___
*[`README.md` line 331 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQih4ttDrDxR2FSXtD7:-NQjdrGr11h65dtb_tOm:bmoylty) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L331)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Btw, this README doesn't mention at all that it is required to have `yarn` installed locally to be able to run tests
</blockquote></details>

added it now
___
*[`README.md` line 351 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQiguBF-6MlSCXX55Tk:-NQjdu37BDa-qf3CBjzh:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L351)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Could be explained how to stop them 
</blockquote></details>

Done.
___
*[`README.md` line 364 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQiiBDsDK0afo_D__9O:-NQjeMC-7eiEYJZ77IMC:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L364)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should these be ran agains generic image or hsl image or both? Or does it matter at all? This could be mentioned too.
</blockquote></details>

Done.
___
*[`README.md` line 387 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQiiemDASmhs0t2B0Xk:-NQjevV67M0DE3uU48kb:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L387)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What does string interpolation mean in this context, or should it be self-evident for everyone?

Edit: actually this can be deduced when reading the final chapters of this README. So this would be easier to understand if we would mention this **after** we explained the concept of string interpolation in our environment, but this is OK too.
</blockquote></details>

Done.
___
*[`README.md` line 441 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQiyaMNCzSOCY4ad6fM:-NQjfFV826fVjYj7fT9J:bwratk8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L441)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This whole section could benefit from some clarification. To be is a bit unclear wtf in the first place we are talking here about. :) 
</blockquote></details>

I don't really have energy to rephrase this text now, it wasn't in scope of this PR. If it feels important, please create a separate ticket about it!
___
*[`README.md` line 454 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQiyTwz9TmLN8wdUaP0:-NQjfiay1NEK9_EmeuwW:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L454)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Could add link for definition of PCRE. Does it mean this? https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions
</blockquote></details>

Done.
___
*[`README.md` line 477 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQj0-0H40f5EhERzm8-:-NQjfpwA0LWK5dbB-C9_:bhew5rh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L477)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Dockerfile says we are using `v2.16.0-ce.cli-migrations-v3`. So this should be updated to reflect that, or maybe just say "The shell in currently used `hasura/graphql-engine` is ..."
</blockquote></details>

tbh this whole section is outdated as hasura 2.0 has bash and regexp support. But this string interpolation script works as intended so no need to simplify it for now.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160)* status: 0 of 3 files reviewed, 19 unresolved discussions (waiting on @Leitsi and @tk-vincit)

___
*[`README.md` line 83 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQe_fnLCa7YHaKPv08n:-NQjnyaj3QMwfUTXdhBi:b-82hyoh) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L83)):*
> done in separate PR
___
*[`README.md` line 93 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQe_wlUEAhzZVNtgTQw:-NQjnuUY-TYkxURfzrPY:b4lm95p) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/4c1039e1586f7aaf036812f2bfb323c4222f5592/README.md#L93)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Same here, split to smaller rows?
</blockquote></details>

done in separate PR

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160)* status: 0 of 3 files reviewed, 20 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`scripts/stop-dependencies.sh` line 3 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/160#-NQkGUwi58UULJY6ebVP:-NQkGUwj7WMPILjhMRzR:ba0x5xg) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/a4c1476e99b3d410f4adc58592d3fc033b817f47/scripts/stop-dependencies.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> # start up test database and hasura for migrations
> ```

Incorrect comment isn't this, copypaste from start script?

**Pull request merged**
