### PR TITLE
Directly read from the Tiamat database

### PR DESCRIPTION
**Pull request by culka**
- Use the default database also as the metadata database
- Create a direct connection to the Tiamat database
- Track all public tables
- Track all relevant parent -> child connections

Resolves https://github.com/HSLdevcom/jore4/issues/1673

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 102 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226)* status: 3 of 102 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`metadata/hsl/databases/databases.yaml` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226#-NtQMJJH2kQU3qFc9AmJ:-NtQMJJH2kQU3qFc9AmK:b-8wgemt) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/145d49f2bc5a3b6704a842aacd6c9aa52d04b6cb/metadata/hsl/databases/databases.yaml#L7)):*
> ```YAML
>       database_url:
>         from_env: HASURA_TIAMAT_DATABASE_URL
>       isolation_level: read-committed
> ```

Other connections have `isolation\_level: serializable`, any special reason for not using that?
___
*[`metadata/hsl/databases/databases.yaml` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226#-NtQLmYYAe9ujFsJZhAx:-NtQLmYYAe9ujFsJZhAy:be4bw8g) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/145d49f2bc5a3b6704a842aacd6c9aa52d04b6cb/metadata/hsl/databases/databases.yaml#L12)):*
> ```YAML
>     naming_convention: hasura-default
>     root_fields:
>       namespace: stop_database
> ```

In other databases we have used plural (which would sound better anyway, in my opinion, because it sounds a bit less like a verb), so should we use `stops_database` here? Also, the folder name `tiamatdb` does not match this, is that fine?

Also `database` -> `db` would be an acceptable abbreviation I think, but this is fine as well.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226)* status: 3 of 102 files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`migrations/generic/metadata/readme.txt` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226#-NtQNhaa6YoUfestV5GM:-NtQNhaa6YoUfestV5GN:bq5awq8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/145d49f2bc5a3b6704a842aacd6c9aa52d04b6cb/migrations/generic/metadata/readme.txt#L1)):*
> ```help
> Otherwise empty folder expected.
> ```

Could elaborate a little, if the purpose of these files is to ensure that the folder exists (for whatever reason).

**Review by culka — COMMENTED** [review]
> Reviewed 7 of 102 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226)* status: 7 of 102 files reviewed, 3 unresolved discussions (waiting on @Leitsi)

___
*[`metadata/hsl/databases/databases.yaml` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226#-NtQMJJH2kQU3qFc9AmJ:-NtQSAMLEYMoCuDcvMRt:b-1zzss3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/145d49f2bc5a3b6704a842aacd6c9aa52d04b6cb/metadata/hsl/databases/databases.yaml#L7)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Other connections have `isolation\_level: serializable`, any special reason for not using that?
</blockquote></details>

No real reason, this should not have any effects because writes are impossible, but let's use the same one.
___
*[`metadata/hsl/databases/databases.yaml` line 12 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226#-NtQLmYYAe9ujFsJZhAx:-NtQSKbWBKVqzLreUI0e:bvy31zx) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/145d49f2bc5a3b6704a842aacd6c9aa52d04b6cb/metadata/hsl/databases/databases.yaml#L12)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

In other databases we have used plural (which would sound better anyway, in my opinion, because it sounds a bit less like a verb), so should we use `stops_database` here? Also, the folder name `tiamatdb` does not match this, is that fine?

Also `database` -> `db` would be an acceptable abbreviation I think, but this is fine as well.
</blockquote></details>

Changed database to `stops_database`
Also yeah, `tiamatdb` should rather be `stops`, changed :+1: 
___
*[`migrations/generic/metadata/readme.txt` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226#-NtQNhaa6YoUfestV5GM:-NtQVOGP9vq6B2c080Th:bb34ugu) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/145d49f2bc5a3b6704a842aacd6c9aa52d04b6cb/migrations/generic/metadata/readme.txt#L1)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could elaborate a little, if the purpose of these files is to ensure that the folder exists (for whatever reason).
</blockquote></details>

Added a better description.

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/226#-:-NtQvgwPEnyjBRQF22AC:bnfp4nl)* status: 3 of 104 files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
