### PR TITLE
Add via information columns

### PR DESCRIPTION
**Pull request by HenrikHartiala**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76)* status: all files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala, @jschummer, and @pallost)

___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N33b2amArS9fYhJro58:-N33b2amArS9fYhJro59:b-8ckcq8) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0b9e28cde84a72078742610e4aef30134417c1ef/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L3)):*
> ```TSQL
> ALTER TABLE journey_pattern.scheduled_stop_point_in_journey_pattern
>     ADD COLUMN via_point_name_i18n JSONB NULL,
>     ADD COLUMN via_point_short_name_i18n JSONB NULL;
> ```

I think a check constraint should be added that guarantees that name and short name (for via point) exist only if `is_via_point = true`.

```sql
ADD CONSTRAINT ck_foo_bar CHECK (via_point_name_i18n IS NULL AND via_point_short_name_i18n IS NULL OR is_via_point = true);

```



_Code quote:_
```TSQL
    ADD COLUMN via_point_name_i18n JSONB NULL,
    ADD COLUMN via_point_short_name_i18n JSONB NULL;
```
___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N33bt9t1vp97gvNnPAn:-N33bt9t1vp97gvNnPAo:b-99ajcu) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0b9e28cde84a72078742610e4aef30134417c1ef/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L4)):*
> ```TSQL
>     ADD COLUMN via_point_name_i18n JSONB NULL,
>     ADD COLUMN via_point_short_name_i18n JSONB NULL;
> CREATE INDEX idx_scheduled_stop_point_in_journey_pattern_via_point_name_i18n
> ```

It would be nice to have some explanation (as a comment) for the justification of index. Like it is "used to filter result sets of SELECT queries". For foreign key references the reasoning is evident but in this case it perhaps isn't.

However, indices may easily be removed later if not needed. So, it is probably safer to just create them if a use case is presumed but initially not 100% sure.



_Code quote:_
```TSQL
CREATE INDEX idx_scheduled_stop_point_in_journey_pattern_via_point_name_i18n
```

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N33b2amArS9fYhJro58:-N34P2OX1F0NF03m3jQR:b722q5d) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0b9e28cde84a72078742610e4aef30134417c1ef/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L3)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think a check constraint should be added that guarantees that name and short name (for via point) exist only if `is_via_point = true`.

```sql
ADD CONSTRAINT ck_foo_bar CHECK (via_point_name_i18n IS NULL AND via_point_short_name_i18n IS NULL OR is_via_point = true);

```

</blockquote></details>

Thanks, Good point. Added constraints on both ways.
___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N33bt9t1vp97gvNnPAn:-N34PEat3Ed1Os4xAN-L:b-yad52m) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0b9e28cde84a72078742610e4aef30134417c1ef/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L4)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It would be nice to have some explanation (as a comment) for the justification of index. Like it is "used to filter result sets of SELECT queries". For foreign key references the reasoning is evident but in this case it perhaps isn't.

However, indices may easily be removed later if not needed. So, it is probably safer to just create them if a use case is presumed but initially not 100% sure.
</blockquote></details>

Yes, the indexes are created currently for the future. I think these were needed when suggesting via point names maybe? But not completely sure.

**Review by jarkkoka — COMMENTED** [review]
Looks good to me. Some minor improvement suggestions that you may consider to apply. No re-review needed from my part.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-:-N34tr2Y2Qh5p4WclW-A:bf74ti5)* status: all files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala, @jschummer, and @pallost)

___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N33bt9t1vp97gvNnPAn:-N34tDpKA-C98uhUsD6x:b-udvmsa) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0b9e28cde84a72078742610e4aef30134417c1ef/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L4)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yes, the indexes are created currently for the future. I think these were needed when suggesting via point names maybe? But not completely sure.
</blockquote></details>

Ok. Then I would prepend the index creation statements with this comment or similar text.

```sql
-- Creation of indexes to be prepared to include names and short names in the name suggestion scheme.
```
___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N34s0Cz3WmXJHrctewA:-N34s0Cz3WmXJHrctewB:b-ntmfki) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/2f94bd05160bacdc5d70695d20a33694181254e1/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L4)):*
> ```TSQL
>     ADD COLUMN via_point_name_i18n JSONB NULL DEFAULT NULL,
>     ADD COLUMN via_point_short_name_i18n JSONB NULL DEFAULT NULL,
>     ADD CONSTRAINT is_via_point
> ```

Not a big deal but I would rename this to `ck_via_point_state` (or something similar) to distinguish it from the column with same name (common `ck` prefix for check constraints like there is `idx` for indices).



_Code quote:_
```TSQL
is_via_point
```
___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 5 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N34u8BaETIzRbDcQnmr:-N34u8BaETIzRbDcQnms:b-56tu0l) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/2f94bd05160bacdc5d70695d20a33694181254e1/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L5)):*
> ```TSQL
>     ADD COLUMN via_point_short_name_i18n JSONB NULL DEFAULT NULL,
>     ADD CONSTRAINT is_via_point
>         CHECK((is_via_point = false AND via_point_name_i18n IS NULL and via_point_short_name_i18n is NULL) OR 
> ```

For style consistency, lowercase `and` and `is` should be changed to uppercase.



_Code quote:_
```TSQL
and via_point_short_name_i18n is NULL
```

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 4 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N33bt9t1vp97gvNnPAn:-N3AJjX38nxjks12zgMI:b-uskhex) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0b9e28cde84a72078742610e4aef30134417c1ef/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L4)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok. Then I would prepend the index creation statements with this comment or similar text.

```sql
-- Creation of indexes to be prepared to include names and short names in the name suggestion scheme.
```
</blockquote></details>

:+1: Thanks!
___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N34s0Cz3WmXJHrctewA:-N3AJY7ACx-dKBaJh5_y:b-8n9n2r) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/2f94bd05160bacdc5d70695d20a33694181254e1/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L4)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Not a big deal but I would rename this to `ck_via_point_state` (or something similar) to distinguish it from the column with same name (common `ck` prefix for check constraints like there is `idx` for indices).
</blockquote></details>

Thanks, I'll use the `ck_via_point_state` one!
___
*[`migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql` line 5 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-N34u8BaETIzRbDcQnmr:-N3AJh-X1HFJQ2Y0XiRt:bwu9ne5) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/2f94bd05160bacdc5d70695d20a33694181254e1/migrations/generic/default/1652430806426_add_via_point_name_to_scheduled_stop_point_in_journey_pattern/up.sql#L5)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

For style consistency, lowercase `and` and `is` should be changed to uppercase.
</blockquote></details>

Thanks for spotting, it seems I was too hasty with this and my negligence lead to this.

**Review by jarkkoka — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/76#-:-N3Ik40h4OzIams7F_oZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer and @pallost)

**Pull request merged**
