### PR TITLE
Test setup refactor

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/134)

### CODE REVIEW

**Comment by Leitsi** [comment]
*[`test/hasura/generic/util/db.ts` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/134#-NM4CILi8U2uPvWQB6wC:-NM4CILj3cjGFJ0SbFbT:bkzbuac) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/cf4383b57b046fad1e1a40f1f08ec6ef8ec87562/test/hasura/generic/util/db.ts#L4)):*
> ```XML
> import { Pool } from 'pg';
> 
> export type DbConnection = Pool | Knex.Transaction;
> ```

One possibe idea to maybe improve these utils. Should we create a new wrapper class/object for these methods here, with dbConnection? Issue: currently you need to pass DbConnection to all methods here.

Eg. in tests one needs to:

```
  let dbConnectionPool: pg.Pool;
  beforeAll(() => {
    dbConnectionPool = new pg.Pool(config.networkDbConfig);
  });
  
  afterAll(() => dbConnectionPool.end());
  
  beforeAll(() => {
    setupDb(
      dbConnectionPool, // this annoys me
      [...])
    );
  });
```

What if we could instead just do:
```
  let dbConnection: DbConnection;
  beforeAll(() => {
    dbConnection = db.createDbConnection(config.networkDbConfig);
  });

  afterAll(() => dbConnection.end());

  beforeAll(() => {
    dbConnection.setupDb(
      [...])
    );
  });
```

Well, not many lines saved. But this would also remove the need to use pg directly in test files.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 57 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/134)* status: 1 of 59 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`test/hasura/generic/datasets/setup.ts` line 31 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/134#-NM44J7LAE7EpTU7E-WG:-NM44J7LAE7EpTU7E-WH:b-hpo73b) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/cf4383b57b046fad1e1a40f1f08ec6ef8ec87562/test/hasura/generic/datasets/setup.ts#L31)):*
> ```XML
>       for (let i = 0; i < tables.length; i++) {
>         const table = tables[i];
>         // eslint-disable-next-line no-await-in-loop
> ```

This eslint override would be avoidable with `await Promise.all(tables.map(table => db.truncate(trx, table.name)));`

Though, same problem arises couple of rows later and this trick doesn't work there without splitting to smaller methods.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/134)* status: 0 of 60 files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`test/hasura/generic/datasets/setup.ts` line 31 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/134#-NM44J7LAE7EpTU7E-WG:-NM87lNP8qzyHfe83oT8:b9lg9d3) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/cf4383b57b046fad1e1a40f1f08ec6ef8ec87562/test/hasura/generic/datasets/setup.ts#L31)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This eslint override would be avoidable with `await Promise.all(tables.map(table => db.truncate(trx, table.name)));`

Though, same problem arises couple of rows later and this trick doesn't work there without splitting to smaller methods.
</blockquote></details>

unfortunately both the truncates and the inserts have to happen in order because of the foreign key constraints... that's why this has to be done sequentially. But I took your idea and made a similar promise wrapper for it
___
*[`test/hasura/generic/util/db.ts` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/134#-NM4CILi8U2uPvWQB6wC:-NM8rD6BCRXBBz5gZNbU:bjjy32o) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/cf4383b57b046fad1e1a40f1f08ec6ef8ec87562/test/hasura/generic/util/db.ts#L4)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

One possibe idea to maybe improve these utils. Should we create a new wrapper class/object for these methods here, with dbConnection? Issue: currently you need to pass DbConnection to all methods here.

Eg. in tests one needs to:

```
  let dbConnectionPool: pg.Pool;
  beforeAll(() => {
    dbConnectionPool = new pg.Pool(config.networkDbConfig);
  });
  
  afterAll(() => dbConnectionPool.end());
  
  beforeAll(() => {
    setupDb(
      dbConnectionPool, // this annoys me
      [...])
    );
  });
```

What if we could instead just do:
```
  let dbConnection: DbConnection;
  beforeAll(() => {
    dbConnection = db.createDbConnection(config.networkDbConfig);
  });

  afterAll(() => dbConnection.end());

  beforeAll(() => {
    dbConnection.setupDb(
      [...])
    );
  });
```

Well, not many lines saved. But this would also remove the need to use pg directly in test files.
</blockquote></details>

this is a good idea but would increase the scope of this PR too much as it would require a small change in all files. I'll do it in a next PR

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/134#-:-NM8v1BB32Z79OIIUWke:bnfp4nl)* status: 0 of 60 files reviewed, all discussions resolved

**Pull request merged**
