### PR TITLE
Recreate seed data for infrastructure links

### PR DESCRIPTION
**Pull request by jarkkoka**
Recreate seed data for infrastructure links in order to keep up with Digiroad data updates in the map-matching service.
Especially, include some bi-directional loop links for testing purposes.

Resolves HSLdevcom/jore4#1060

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/120)

### CODE REVIEW

**Review by eleksi — COMMENTED** [review]
Please also add vehicle submodes for added infrastructure links, e.g. by changing migration order so that `vehicle_submode_on_infrastructure_link` seed comes after this new seed migration.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/120#-:-NI2dFWZAXJEFHmZb20S:b-gzgd19)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @culka and @pallost)

**Review by jarkkoka — COMMENTED** [review]
Thanks for the comment regarding the vehicle submodes! Now they are included.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/120#-:-NIfnJMn7Z-7TElh4y9L:b2ase80)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @culka and @pallost)

**Review by pallost — CHANGES_REQUESTED** [review]
Have you verified how long does it take now for this image to start up? If it's much more than 10 seconds then it would slow down development maybe too much. If it takes longer then let's replace INSERTs with COPY. If it still starts up relatively fast, then I approve this PR

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/120#-:-NIlnUTN8rmRwUSKhol0:b-mbc6d9)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @culka)

**Review by jarkkoka — COMMENTED** [review]
In my local setup, infrastructure links are populated in less than a second.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/120#-:-NIlzfDQ-_jFgJoka0em:b9ixj1c)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
