### PR TITLE
Add timing point constraints and tests

### PR DESCRIPTION
**Pull request by HenrikHartiala**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala)

___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts` line 26 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ8tWv2cwx526XoGJD:-NbJ8tWv2cwx526XoGJE:b23g8mo) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts#L26)):*
> ```XML
> };
> 
> const buildMutation = (
> ```

Same mutations in both insert tests, same with updates. Would it make sense to share these via `test/hasura/generic/timetablesdb/mutations.ts`?

Or maybe rather, should we combine the separate with and without conflicts suites under one file? I don't see much reason to keep them separate.
___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts` line 42 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ8QeLAgnjIXTkkdwB:-NbJ8QeLAgnjIXTkkdwC:bavb8i8) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts#L42)):*
> ```XML
> `;
> 
> describe('Inserting scheduled_stop_point_on_journey_pattern with constraint conflicts', () => {
> ```

These are all under `integration-tests/mutations` but would this be more of a `integration-tests/data-integrity` material? The unit under test is a DB constraint which ensures data integrity, even if it is tested via mutations.
___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-without-conflicts.spec.ts` line 62 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ9Bzt18km8T-Qfq0o:-NbJ9Bzt18km8T-Qfq0p:bvgg9h6) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-without-conflicts.spec.ts#L62)):*
> ```XML
>     });
>   });
>   describe('used as timing point but not as regulated timing point', () => {
> ```

Newlines before each describe.

Could maybe be automated with https://github.com/dangreenisrael/eslint-plugin-jest-formatting or something?
___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/update-with-conflicts.spec.ts` line 33 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ9Ut19jZy83deOMv1:-NbJ9Ut28_Y0rhoi1its:blmbbjw) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/update-with-conflicts.spec.ts#L33)):*
> ```XML
> 
>           ${getPropNameArray(scheduledStopPointInJourneyPatternProps).join(',')}
> ```

Unnecessary line breaks here. Same in the other update suite.
___
*[`test/hasura/util/response.ts` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ5rU7Ek-n5lKArzsS:-NbJ5rU7Ek-n5lKArzsT:bory5e5) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/util/response.ts#L11)):*
> ```XML
>  * making this a normal function, or by making the function name more
>  * precise. Also the expectedErrorMsg is actually expectedErrorMsgSubstring
>  */
> ```

To be honest, I would rather leave this TODO out. If there's some clearly better solution, just implement it. I don't see too much problem with current implementation, even if it works differently from the other function.

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala and @Leitsi)

___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts` line 42 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ8QeLAgnjIXTkkdwB:-NbwwJgtB4gOvQbm42rt:b-motz5h) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts#L42)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

These are all under `integration-tests/mutations` but would this be more of a `integration-tests/data-integrity` material? The unit under test is a DB constraint which ensures data integrity, even if it is tested via mutations.
</blockquote></details>

This is a bit double-edged sword. Now that these tests are in the "mutations" folder, it can be seen that the underlying DB constraint is just a technical detail used to implement the actual business logic constraint. So now this test code being in this folder, it is focused on that both mutations (insert and update) behave well as per the business logic definition.

If we just want to test that the DB constraint is in effect, then it would be enough to test just one case (insert OR update). Clearly the former approach has been initially selected.

**Review by HenrikHartiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193)* status: 3 of 16 files reviewed, 5 unresolved discussions (waiting on @jarkkoka and @Leitsi)

___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts` line 26 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ8tWv2cwx526XoGJD:-NbwsxPi6IFqREUk92gf:b-uyfw43) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts#L26)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Same mutations in both insert tests, same with updates. Would it make sense to share these via `test/hasura/generic/timetablesdb/mutations.ts`?

Or maybe rather, should we combine the separate with and without conflicts suites under one file? I don't see much reason to keep them separate.
</blockquote></details>

I can combine these yeah, basically I saw the insert- and update- in the other test files as prefix, but with this constraint it's probably best to have them together.
___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts` line 42 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ8QeLAgnjIXTkkdwB:-NbwrhnxAV9D609-V7Te:b-xnnmv0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts#L42)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

These are all under `integration-tests/mutations` but would this be more of a `integration-tests/data-integrity` material? The unit under test is a DB constraint which ensures data integrity, even if it is tested via mutations.
</blockquote></details>

Good point, I was trying to mimic some older tests locations and naming, which now I see are a bit everywhere. Some seems to be under `integration-tests` and some I might have just checked wrong. But yeah I'll move these under data-integrity :+1: 
___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-without-conflicts.spec.ts` line 62 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ9Bzt18km8T-Qfq0o:-Nbwv6ir4qCcKiMEm-fl:b-iwzbks) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-without-conflicts.spec.ts#L62)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Newlines before each describe.

Could maybe be automated with https://github.com/dangreenisrael/eslint-plugin-jest-formatting or something?
</blockquote></details>

Fixed :+1: and also added the eslint plugin with recommended settings :ok_hand: 
___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/update-with-conflicts.spec.ts` line 33 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ9Ut19jZy83deOMv1:-Nbwxdyg5P_WfVZ7fgmX:b-bs17ia) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/update-with-conflicts.spec.ts#L33)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Unnecessary line breaks here. Same in the other update suite.
</blockquote></details>

Check! removed
___
*[`test/hasura/util/response.ts` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ5rU7Ek-n5lKArzsS:-NbwtXL34niUyG4HgSca:b-dluixx) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/util/response.ts#L11)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

To be honest, I would rather leave this TODO out. If there's some clearly better solution, just implement it. I don't see too much problem with current implementation, even if it works differently from the other function.
</blockquote></details>

Understandable, we also already discussed about this and there is a ticket about this, so I'll drop this whole comment commit out :+1:

**Review by Leitsi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193)* status: 4 of 16 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala and @jarkkoka)

___
*[`test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts` line 26 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-NbJ8tWv2cwx526XoGJD:-NbxhQyg4S3_AqcqPQTW:b-71d6ct) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/85867167ade02e8d793c1136ead15eeebdcaec27/test/hasura/generic/networkdb/integration-tests/mutations/timing-point-constraints/insert-with-conflicts.spec.ts#L26)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I can combine these yeah, basically I saw the insert- and update- in the other test files as prefix, but with this constraint it's probably best to have them together.
</blockquote></details>

Sorry for ambiquity, but I actually meant combining `insert-with-conflicts` and `insert-without-conflicts` -> `insert`, and same for updates. Though this is fine as well.

But there's still the same problem as before, that there's ~40 rows copypasted code between the two test files (just outside the outer describe). Well, maybe just leave it like this or combine further.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193)* status: 4 of 16 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala and @jarkkoka)

___
*[`test/hasura/generic/networkdb/integration-tests/data-integrity/timing-point-constraints/insert-and-update.spec.ts` line 63 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-Nbxr262A3FL4D5dY2ZL:-Nbxr262A3FL4D5dY2ZM:b5in9fz) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/01ca5f7f9fba019de1cc8fd7d83a82d243d60089/test/hasura/generic/networkdb/integration-tests/data-integrity/timing-point-constraints/insert-and-update.spec.ts#L63)):*
> ```XML
> `;
> 
> describe('Inserting and updating scheduled_stop_point_on_journey_pattern with timing point constraint conflicts', () => {
> ```

I would generally like to avoid multiple top level describes in a file: if one is using the `.only` or `.skip` features, it is rather easy to miss that there are multiple describes in a file.

So, maybe structure like this instead:
```
describe('Inserting and updating scheduled_stop_point_on_journey_pattern', () => {
  let dbConnection: DbConnection;

  beforeAll(() => {
    dbConnection = createDbConnection(config.networkDbConfig);
  });

  afterAll(() => closeDbConnection(dbConnection));

  beforeEach(() => setupDb(dbConnection, routesAndJourneyPatternsTableData));

  describe('with timing point constraint conflicts', () => { ... });

  describe('without timing point constraint conflicts', () => { ... });
});
```

Unfortunately it doesn't look like we can check this with linter. There's some plugin for mocha ( see https://stackoverflow.com/questions/39436530/enforce-one-describe-per-file ) but didn't seem like it for Jest.

**Review by Leitsi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/193#-:-NcMH9cE7v_TjF2-9EgY:bnfp4nl)* status: 4 of 16 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala and @jarkkoka)

**Pull request merged**
