### PR TITLE
Add support for hidden route variants

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121)* status: all files reviewed, 6 unresolved discussions (waiting on @eleksi)

___
*[`migrations/generic/default/1610000000000_squashed_dump/up.sql` line 195 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NImn2bt9brDAvATMKpr:-NImn2bv0mEkcikj_W4u:b-s6aikc) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/f99c7b0c24b7e56a7214ca3ea4889dbd92a4f979/migrations/generic/default/1610000000000_squashed_dump/up.sql#L195)):*
> ```TSQL
>     priority integer NOT NULL,
>     label text NOT NULL,
>     variant smallint CHECK (variant >= 0),
> ```

This new column should be introduced in a new migration script with: `ALTER TABLE ADD COLUMN ...`.

Editing an existing migration script is not the correct way to make schema changes except for functions which are created in repeatable migration scripts.

Is zero really the lowest variant number or should it be one?



_Code quote:_
```TSQL
variant smallint CHECK (variant >= 0),
```
___
*[`migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NImnt5K4dm3jxpKwi_u:-NImnt5K4dm3jxpKwi_v:bierpya) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/f99c7b0c24b7e56a7214ca3ea4889dbd92a4f979/migrations/generic/default/2000000000004_R_after_migrate_create_journey_pattern/up.sql#L12)):*
> ```TSQL
>   --  2,     2022-01-01,   2027-01-01,    A,   20
>   entity AS (
>     SELECT r.route_id AS id, r.validity_start, r.validity_end, r.label AS key1, r.direction AS key2, r.variant as key3, r.priority
> ```

I would put these in reverse order like this:

`r.variant AS key2, r.direction AS key3`



_Code quote:_
```TSQL
r.direction AS key2, r.variant as key3
```
___
*[`migrations/generic/default/2000000000006_R_after_migrate_create_route/up.sql` line 208 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NImrcL45KzfIY6yilpi:-NImrcL45KzfIY6yilpj:bqxkntw) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/f99c7b0c24b7e56a7214ca3ea4889dbd92a4f979/migrations/generic/default/2000000000006_R_after_migrate_create_route/up.sql#L208)):*
> ```TSQL
> 
> ALTER TABLE ONLY route.route
>     ADD CONSTRAINT route_unique_validity_period EXCLUDE USING gist (label WITH =, coalesce(variant,-1) WITH =, direction WITH =, priority WITH =, internal_utils.daterange_closed_upper(validity_start, validity_end) WITH &&) WHERE ((priority < internal_utils.const_priority_draft()));
> ```

I am wondering how this `ALTER TABLE ... ADD CONSTRAINT ...` really works in a repeatable migration script since this already exists...



_Code quote:_
```TSQL
ALTER TABLE ONLY route.route
    ADD CONSTRAINT route_unique_validity_period EXCLUDE USING gist (label WITH =, coalesce(variant,-1) WITH =, direction WITH =, priority WITH =, internal_utils.daterange_closed_upper(validity_start, validity_end) WITH &&) WHERE ((priority < internal_utils.const_priority_draft()));
```
___
*[`migrations/seed-data/default/2524600800000_seed-routes/up.sql` line 750 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NImsC3L33VN-agWEoR1:-NImsC3L33VN-agWEoR2:b7lksr3) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/f99c7b0c24b7e56a7214ca3ea4889dbd92a4f979/migrations/seed-data/default/2524600800000_seed-routes/up.sql#L750)):*
> ```TSQL
>   label,
>   direction,
>   variant
> ```

It would be more intuitive if you switched the order of these two columns...but not required as it affects many other insert rows below.



_Code quote:_
```TSQL
  direction,
  variant
```
___
*[`test/hasura/integration-tests/data-integrity/line-routes/variant/insert-route.spec.ts` line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NImvOYD2qY1-_yRRBTT:-NImvOYE6Kcxiw7rbteT:bz44dnq) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/f99c7b0c24b7e56a7214ca3ea4889dbd92a4f979/test/hasura/integration-tests/data-integrity/line-routes/variant/insert-route.spec.ts#L60)):*
> ```XML
>     onLineId: string | undefined,
>     variant: number | null,
>     expectedErrorMsg?: string,
> ```

This seems to be unused in this file. Did you really mean to check the error responses?



_Code quote:_
```XML
expectedErrorMsg?: string
```
___
*[`test/hasura/integration-tests/priority-and-validity-period-constraints/route/insert-without-conflicts.spec.ts` line 124 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NImthorD6b6h_11lKB0:-NImthos09mbyXQHFDf_:b9uigzb) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/f99c7b0c24b7e56a7214ca3ea4889dbd92a4f979/test/hasura/integration-tests/priority-and-validity-period-constraints/route/insert-without-conflicts.spec.ts#L124)):*
> ```XML
>       variant: 3,
>       priority: 10,
>       validity_start: new LocalDate('2054-09-02'),
> ```

`2044-05-02` would be identical to what is defined for route `1` in `datasets/defaultSetup/routes.ts`. By using that value, the only difference would be the variant number, which is tested here.



_Code quote:_
```XML
2054-09-02
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121)* status: all files reviewed, 6 unresolved discussions (waiting on @eleksi and @jarkkoka)

___
*[`migrations/generic/default/1610000000000_squashed_dump/up.sql` line 195 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NImn2bt9brDAvATMKpr:-NJ4YkeI868UFZaxA1VS:bjif8m4) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/f99c7b0c24b7e56a7214ca3ea4889dbd92a4f979/migrations/generic/default/1610000000000_squashed_dump/up.sql#L195)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This new column should be introduced in a new migration script with: `ALTER TABLE ADD COLUMN ...`.

Editing an existing migration script is not the correct way to make schema changes except for functions which are created in repeatable migration scripts.

Is zero really the lowest variant number or should it be one?
</blockquote></details>

how do we handle default variants? variant = 0? or variant = NULL?

**Review by jarkkoka — APPROVED** [review]
> Reviewed 4 of 8 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121)* status: all files reviewed, 4 unresolved discussions (waiting on @eleksi)

___
*[`migrations/generic/default/1670837938775_add_route_variant/down.sql` line 2 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NJACTck7OL_a5nfomQt:-NJACTck7OL_a5nfomQu:ba42s0o) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/285fad18c88bbe50289f152d3bba4b04b0604792/migrations/generic/default/1670837938775_add_route_variant/down.sql#L2)):*
> ```TSQL
> ALTER TABLE route.route
>   DROP COLUMN variant CASCADE; /* TODO: Remove cascade after fixing repeatable down migrations */
> ```

We've had a convention to use the other SQL comment syntax (starting with three characters `-- `) - especially, for one-line comments.

By looking at the code in this PR, the cascading currently affects these functions/constraints:
1. `journey_pattern.maximum_priority_validity_spans`
2. `journey_pattern.get_broken_route_journey_patterns`
3. `route.insert_route`
4. `route.update_route`
5. `route_unique_validity_period`
6. `route_variant_unsigned_check`

So quite a lot. Fixing the "down" path of repeatable migrations by dropping all the functions and constraints they create on the "up" path would allow the `cascade` to be removed.



_Code quote:_
```TSQL
 /* TODO: Remove cascade after fixing repeatable down migrations */
```
___
*[`migrations/generic/default/2000000000006_R_after_migrate_create_route/up.sql` line 208 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NImrcL45KzfIY6yilpi:-NJ5QwAl-tz05OoJd-UK:b6f4cmh) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/f99c7b0c24b7e56a7214ca3ea4889dbd92a4f979/migrations/generic/default/2000000000006_R_after_migrate_create_route/up.sql#L208)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

The constraint is dumped first and then added, so it should work.
</blockquote></details>

Ok, figured this out. There is so called before-migrate-hook that drops the constraints.
___
*[`migrations/generic/default/2000000000006_R_after_migrate_create_route/up.sql` line 259 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NJ5R8C45vYjG7d-OGGP:-NJ5R8C45vYjG7d-OGGQ:b-ju08co) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/285fad18c88bbe50289f152d3bba4b04b0604792/migrations/generic/default/2000000000006_R_after_migrate_create_route/up.sql#L259)):*
> ```TSQL
> 
> ALTER TABLE route.route
>     ADD CONSTRAINT route_variant_unsigned_check CHECK (variant >= 0);
> ```

Looks like the end-of-line character is missing.



_Code quote:_
```TSQL
 
```
___
*[`migrations/seed-data/default/2524600800000_seed-routes/up.sql` line 750 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NImsC3L33VN-agWEoR1:-NJ5RIWwC7or4-EZI2r7:b-wq22e5) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/f99c7b0c24b7e56a7214ca3ea4889dbd92a4f979/migrations/seed-data/default/2524600800000_seed-routes/up.sql#L750)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This was an excellent opportunity to learn how multi cursor works.
</blockquote></details>

Nice. :)

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @jarkkoka)

___
*[`migrations/generic/default/1670837938775_add_route_variant/down.sql` line 2 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NJACTck7OL_a5nfomQt:-NJFOBGs1ov8ITeIRTfY:b3uh7pu) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/285fad18c88bbe50289f152d3bba4b04b0604792/migrations/generic/default/1670837938775_add_route_variant/down.sql#L2)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

We've had a convention to use the other SQL comment syntax (starting with three characters `-- `) - especially, for one-line comments.

By looking at the code in this PR, the cascading currently affects these functions/constraints:
1. `journey_pattern.maximum_priority_validity_spans`
2. `journey_pattern.get_broken_route_journey_patterns`
3. `route.insert_route`
4. `route.update_route`
5. `route_unique_validity_period`
6. `route_variant_unsigned_check`

So quite a lot. Fixing the "down" path of repeatable migrations by dropping all the functions and constraints they create on the "up" path would allow the `cascade` to be removed.
</blockquote></details>

Comment fixed. 

Yep, unfortunately it affects a lot of functions and constraints... But an issue was created to fix the down migrations, so that will fix this as well.
___
*[`migrations/generic/default/2000000000006_R_after_migrate_create_route/up.sql` line 259 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/121#-NJ5R8C45vYjG7d-OGGP:-NJFObeh5J-gcrqSA2wS:bo3t3d0) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/285fad18c88bbe50289f152d3bba4b04b0604792/migrations/generic/default/2000000000006_R_after_migrate_create_route/up.sql#L259)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Looks like the end-of-line character is missing.
</blockquote></details>

Oh, I added it now.

**Pull request merged**
