### PR TITLE
Add transport target to line

### PR DESCRIPTION
**Pull request by eleksi**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[Dockerfile, line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-MzxoVHi6VnI01CGZ9f_:-MzxoVHj2rVCNF_WC5TQ:b-m3emy7) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/Dockerfile#L22)):*
> ```Dockerfile
> 
> # extend the hasura-hsl image to also load some seed data as migrations
> FROM hasura-hsl AS hasura-seed
> ```

let's also patch the metadata to include the new tables and relationships for the hsl-specific schema

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @eleksi and @pallost)

___
*[.github/workflows/cd.yml, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-Mzxpbe51Zm7iMir-y_k:-Mzxpbe51Zm7iMir-y_l:b-cb8f4t) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/.github/workflows/cd.yml#L37)):*
> ```YAML
>             --target hasura-hsl \
>             --cache-from=$IMAGE_NAME:latest \
>             -t $IMAGE_NAME:hsl-$COMMIT_ID \
> ```

you also wanna tag this with
`-t $IMAGE_NAME:hsl`
___
*[.github/workflows/cd.yml, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-Mzxoy077Cz65lhx8nZ8:-Mzxoy077Cz65lhx8nZ9:b-mjr1d5) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/.github/workflows/cd.yml#L42)):*
> ```YAML
>           docker build \
>             --target hasura-seed \
>             --cache-from=$IMAGE_NAME:hsl:latest \
> ```

:hsl:latest is an invalid tag. Did you mean `$IMAGE_NAME:hsl`?
___
*[.github/workflows/cd.yml, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-Mzxpk8C51sg-N4rG7kD:-Mzxpk8C51sg-N4rG7kE:b-omp3cf) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/.github/workflows/cd.yml#L60)):*
> ```YAML
>       - name: Push :latest tag to Docker Hub
>         if: ${{ github.ref == 'refs/heads/main' }}
>         run: docker push $IMAGE_NAME:latest
> ```

should also push `$IMAGE_NAME:hsl`

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @eleksi and @pallost)

___
*[.github/workflows/cd.yml, line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-MzxqYyK4dvz8-VGSG4z:-MzxqYyK4dvz8-VGSG5-:b7jtb4q) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/.github/workflows/cd.yml#L55)):*
> ```YAML
>         run: |
>           docker push $IMAGE_NAME:$COMMIT_ID
>           docker push $IMAGE_NAME:hsl-$COMMIT_ID
> ```

please also change the flux repo auto-updater script to start watching for changes with `hsl-main` prefix from now on:
https://github.com/HSLdevcom/jore4-flux/blob/main/.github/workflows/auto-update.yml#L31

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 118 files reviewed, 7 unresolved discussions (waiting on @eleksi and @pallost)

___
*[.github/workflows/cd.yml, line 31 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N-NRWB90cqTkKXJCxTc:-N-NRWB90cqTkKXJCxTd:b-v1386m) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/848f862325e2d8df8defd802fc62d9651ceae8a3/.github/workflows/cd.yml#L31)):*
> ```YAML
>             --cache-from=$IMAGE_NAME:latest \
>             -t $IMAGE_NAME:latest \
>             -t $IMAGE_NAME:$COMMIT_ID \
> ```

should tag this one as:
-t $IMAGE_NAME:generic
-t $IMAGE_NAME:generic-$COMMIT_ID
___
*[.github/workflows/cd.yml, line 37 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N-NSnWqCxWNnebwLt7f:-N-NSnWqCxWNnebwLt7g:bkabuf) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/848f862325e2d8df8defd802fc62d9651ceae8a3/.github/workflows/cd.yml#L37)):*
> ```YAML
>             --target hasura-hsl \
>             --cache-from=$IMAGE_NAME:latest \
>             -t $IMAGE_NAME:hsl \
> ```

this could be the latest

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 119 files reviewed, 7 unresolved discussions (waiting on @pallost)

___
*[Dockerfile, line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-MzxoVHi6VnI01CGZ9f_:-N-2a5PE-aRsjuybHrgR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/Dockerfile#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's also patch the metadata to include the new tables and relationships for the hsl-specific schema
</blockquote></details>

Done.
___
*[.github/workflows/cd.yml, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-Mzxpbe51Zm7iMir-y_k:-N-2aMME2RSOnKkTqTPg:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/.github/workflows/cd.yml#L37)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you also wanna tag this with
`-t $IMAGE_NAME:hsl`
</blockquote></details>

Done.
___
*[.github/workflows/cd.yml, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-Mzxoy077Cz65lhx8nZ8:-N-2aMa58ew0UfGPTiNu:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/.github/workflows/cd.yml#L42)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

:hsl:latest is an invalid tag. Did you mean `$IMAGE_NAME:hsl`?
</blockquote></details>

Done.
___
*[.github/workflows/cd.yml, line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-MzxqYyK4dvz8-VGSG4z:-N0-afQCEBivPYV3w161:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/.github/workflows/cd.yml#L55)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please also change the flux repo auto-updater script to start watching for changes with `hsl-main` prefix from now on:
https://github.com/HSLdevcom/jore4-flux/blob/main/.github/workflows/auto-update.yml#L31
</blockquote></details>

Done.
___
*[.github/workflows/cd.yml, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-Mzxpk8C51sg-N4rG7kD:-N-NJBgt-2dRpH3TaEew:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/75041c97244c03fd0950624391a0306847188142/.github/workflows/cd.yml#L60)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should also push `$IMAGE_NAME:hsl`
</blockquote></details>

Done.
___
*[.github/workflows/cd.yml, line 31 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N-NRWB90cqTkKXJCxTc:-N0-adEI5xNr_YJPZC4r:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/848f862325e2d8df8defd802fc62d9651ceae8a3/.github/workflows/cd.yml#L31)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should tag this one as:
-t $IMAGE_NAME:generic
-t $IMAGE_NAME:generic-$COMMIT_ID
</blockquote></details>

Done.
___
*[.github/workflows/cd.yml, line 37 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N-NSnWqCxWNnebwLt7f:-N0-adXe5oPq9PbA-JbU:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/848f862325e2d8df8defd802fc62d9651ceae8a3/.github/workflows/cd.yml#L37)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this could be the latest
</blockquote></details>

Done.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 119 files reviewed, 11 unresolved discussions (waiting on @eleksi and @pallost)

___
*[Dockerfile, line 21 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FSP8h4TbyvCcIXFzy:-N0FSP8h4TbyvCcIXFzz:b5nvuxu) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L21)):*
> ```Dockerfile
> FROM hasura-generic AS hasura-hsl
> # install yq
> RUN apt-get update && apt-get install -y gnupg2 software-properties-common
> ```

you should group these into a single RUN command:

```
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64 && \
    add-apt-repository ppa:rmescandon/yq && \
    apt-get update && \
    apt-get install -y yq gnupg2 software-properties-common
```
___
*[Dockerfile, line 27 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FSfHz8PaCQzE9zHjh:-N0FSfI--Bd7u483a5rN:b9nrjnt) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L27)):*
> ```Dockerfile
> RUN apt-get install yq -y
> 
> COPY ./migrations/hsl/default "${HASURA_GRAPHQL_MIGRATIONS_DIR}/default/"
> ```

can't you just COPY the base ./migrations/hsl directory (without default)? Will the destination folder get overwritten if you do so?
`COPY ./migrations/hsl "${HASURA_GRAPHQL_MIGRATIONS_DIR}"`
___
*[Dockerfile, line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FSszZAHq4gmBv5rJi:-N0FSszZAHq4gmBv5rJj:b-893rnx) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L29)):*
> ```Dockerfile
> COPY ./migrations/hsl/default "${HASURA_GRAPHQL_MIGRATIONS_DIR}/default/"
> COPY ./metadata/hsl "${HASURA_GRAPHQL_METADATA_DIR}"
> WORKDIR /
> ```

I don't think you need to change the workdir
___
*[Dockerfile, line 35 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FTY-c7d-p-O6qby5e:-N0FTY-c7d-p-O6qby5f:b-1otk1s) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L35)):*
> ```Dockerfile
> # extend the hasura-hsl image to also load some seed data as migrations
> FROM hasura-hsl AS hasura-seed
> COPY ./migrations/seed-data/default "${HASURA_GRAPHQL_MIGRATIONS_DIR}/default/"
> ```

let's leave an empty line at the end of the file
___
*[README.md, line 114 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FTeanDOP-1n0jNhMM:-N0FTeanDOP-1n0jNhMN:b-106pzi) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/README.md#L114)):*
> ```Markdown
> ### Add/modify HSL specific schema
> 
> You can add HSL specifig schema changes by updating files in `migrations/hsl` and `metadata/hsl` directories. 
> ```

typo: "specific" :)
___
*[README.md, line 115 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FTpdl0mn1QMTrZeoI:-N0FTpdl0mn1QMTrZeoJ:b4y37au) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/README.md#L115)):*
> ```Markdown
> 
> You can add HSL specifig schema changes by updating files in `migrations/hsl` and `metadata/hsl` directories. 
> The folder structure follows the same structure as the original ones. Generic migrations are located in 
> ```

maybe mention that "Generic (Transmodel compatible) migrations"
___
*[README.md, line 120 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FU6CX3ypX6pY76SWA:-N0FU6CX3ypX6pY76SWB:b-9wvopg) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/README.md#L120)):*
> ```Markdown
> When adding new metadata files, they can be added in the `metadata/hsl` directory in the correct location.
> However, when adding content to existing metadata files, a new file should be created in the 
> directory of patched file, inside `/patch` directory. The added file hould only contain the new lines to be added.
> ```

typo: "should"

did you mean: "inside `metadata/hsl/patch` directory"...?

do you also have to have a matching name with the source file in the patch directory? E.g. the generic `route_line.yaml` is patched with a file also called `route_line.yaml`? If so, could you mention that in the README?
___
*[README.md, line 124 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FUNpN1JZAk7u8Og79:-N0FUNpN1JZAk7u8Og7A:bljkr4l) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/README.md#L124)):*
> ```Markdown
> For example, to add a new HSL specific relationship to `route_line` table, a new file should be created.
> 
> `/metadata/hsl/databases/detault/tables/patch/route_line.yaml`:
> ```

good README!
___
*[.github/workflows/cd.yml, line 38 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FVDhFEf1Ie705ZwlB:-N0FVDhFEf1Ie705ZwlC:bis40a6) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/.github/workflows/cd.yml#L38)):*
> ```YAML
>             --cache-from=$IMAGE_NAME:generic \
>             -t $IMAGE_NAME:latest \
>             -t $IMAGE_NAME:$COMMIT_ID \
> ```

you are not pushing the $IMAGE_NAME:$COMMIT_ID to docker hub, to this is an unnecessary tag. But also, maybe we shouldn't even produce a $COMMIT_ID tag without a generic/hsl/seed prefix, it's just gonna confuse things...
___
*[docker/docker-compose.custom.yml, line 9 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FVVUjDo0PSPe6tRub:-N0FVVUjDo0PSPe6tRuc:bkxomvl) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/docker/docker-compose.custom.yml#L9)):*
> ```YAML
>     build:
>       context: ..
>       target: hasura-generic
> ```

we should rather target the `hasura-hsl` image here as that's what we are working with
___
*[scripts/merge-metadata.sh, line 4 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FWRDL-R7_8hn15Nk2:-N0FWRDL-R7_8hn15Nk3:b-j4xmku) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/scripts/merge-metadata.sh#L4)):*
> ```Shell
> 
> # Merge HSL specific metadata with base metadata
> base_dir=.$1/databases/default/tables
> ```

nice work!

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 119 files reviewed, 9 unresolved discussions (waiting on @pallost)

___
*[Dockerfile, line 21 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FSP8h4TbyvCcIXFzy:-N0FaHmh-svfVbgSucOL:b-mjt879) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you should group these into a single RUN command:

```
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64 && \
    add-apt-repository ppa:rmescandon/yq && \
    apt-get update && \
    apt-get install -y yq gnupg2 software-properties-common
```
</blockquote></details>

gnupg2 and software-properties-common are required for the latter steps to succeed. I grouped these RUN commands like you suggested, but left gnupg2 and software-properties-common installation on its own row.
___
*[Dockerfile, line 27 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FSfHz8PaCQzE9zHjh:-N0FaX_16w4zqpXBQd58:b-pnwgre) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L27)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

can't you just COPY the base ./migrations/hsl directory (without default)? Will the destination folder get overwritten if you do so?
`COPY ./migrations/hsl "${HASURA_GRAPHQL_MIGRATIONS_DIR}"`
</blockquote></details>

Well I think I could. Default was part of the seed data copy command before these changes, so I just used the same pattern here.
___
*[Dockerfile, line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FSszZAHq4gmBv5rJi:-N0FdixA3Ub8n4TdMCy4:b-jte4op) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L29)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't think you need to change the workdir
</blockquote></details>

This was actually a row I added after long and confusing debugging. The metadata merging script does not work without this. It could be fixed also by handling paths in the script differently, but this seems like a good enough fix at least for me.
___
*[Dockerfile, line 35 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FTY-c7d-p-O6qby5e:-N0FbNV00gg_5fgYmWbH:bducpjr) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's leave an empty line at the end of the file
</blockquote></details>

Good point. IDE usually takes care of that, but when editing Dockerfile.
___
*[README.md, line 115 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FTpdl0mn1QMTrZeoI:-N0Fbj1dE1iQy1ViyvJh:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/README.md#L115)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

maybe mention that "Generic (Transmodel compatible) migrations"
</blockquote></details>

Done.
___
*[README.md, line 124 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FUNpN1JZAk7u8Og79:-N0FcftW14VCFlmkeDdt:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/README.md#L124)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

good README!
</blockquote></details>

Done.
___
*[.github/workflows/cd.yml, line 38 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FVDhFEf1Ie705ZwlB:-N0Fcnxz9mr1MN6CEORS:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/.github/workflows/cd.yml#L38)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you are not pushing the $IMAGE_NAME:$COMMIT_ID to docker hub, to this is an unnecessary tag. But also, maybe we shouldn't even produce a $COMMIT_ID tag without a generic/hsl/seed prefix, it's just gonna confuse things...
</blockquote></details>

Done.
___
*[docker/docker-compose.custom.yml, line 9 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FVVUjDo0PSPe6tRub:-N0FcotV30Pc5GLJ_k83:b-xnze0w) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/docker/docker-compose.custom.yml#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we should rather target the `hasura-hsl` image here as that's what we are working with
</blockquote></details>

Ended up keeping it as hasura-generic, so test don't have to be altered for hsl specific changes.
___
*[scripts/merge-metadata.sh, line 4 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FWRDL-R7_8hn15Nk2:-N0FdAzm0Hny7AM6D6mE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/scripts/merge-metadata.sh#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

nice work!
</blockquote></details>

Done.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 119 files reviewed, 1 unresolved discussion (waiting on @eleksi and @pallost)

___
*[Dockerfile, line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FSszZAHq4gmBv5rJi:-N0G5El-AQU_YDznjjTV:bxdhpmy) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L29)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This was actually a row I added after long and confusing debugging. The metadata merging script does not work without this. It could be fixed also by handling paths in the script differently, but this seems like a good enough fix at least for me.
</blockquote></details>

let's rather fix the script instead of moving the working directory. Because if you move the workdir, the "command" and "entrypoint" attributes will start working different. Could you try adding this to the beginning of your merge script?

```
# allow running from any working directory
WD=$(dirname "$0")
cd "${WD}"
```

if this doesn't work then please reset the workdir back to `/app` after this following `RUN` command

**Review by eleksi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 119 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[`Dockerfile` line 29 at r4](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63#-N0FSszZAHq4gmBv5rJi:-N0VPAXb9S1W8b7iuCPT:b-srtxtv) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/5bd7a1b12acfe10de3fa1117f441a3ad9c4db963/Dockerfile#L29)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's rather fix the script instead of moving the working directory. Because if you move the workdir, the "command" and "entrypoint" attributes will start working different. Could you try adding this to the beginning of your merge script?

```
# allow running from any working directory
WD=$(dirname "$0")
cd "${WD}"
```

if this doesn't work then please reset the workdir back to `/app` after this following `RUN` command
</blockquote></details>

I tried it but it didn't work. I reset the workdir.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/63)* status: 0 of 119 files reviewed, all discussions resolved (waiting on @pallost)

**Comment by eleksi** [comment]
e2e tests pass in this manually triggered run that uses correct versions of ui and hasura images.

https://github.com/HSLdevcom/jore4-robot/actions/runs/2219903238

**Pull request merged**
