### PR TITLE
Stops to table

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102)

### CODE REVIEW

**Review by jschummer — CHANGES_REQUESTED** [review]
Nice work, some small findings only!

Have you by any chance tested that the importer does work with the updated privileges? Not a must, but good to keep in mind that someone should probably test this (possibly me..).

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-:-NFxcJVu6DXZgeikfPc0:buinj6a)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`-- commits` line 7 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-NFxah40-4w5nXfCRWn7):*
I suppose this line should be removed, since `insert_scheduled_stop_point_with_vehicle_mode` is left in the `internal_service_pattern`?



_Code quote:_
```
 move all functions and tables from internal_service_pattern schema to service_pattern schema
```
___
*[`migrations/generic/default/1666001572785_remove_scheduled_stop_view/up.sql` line 607 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-NFx_CePE4b73aSlzvDi:-NFx_CePE4b73aSlzvDj:bwyjy48) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/fc3fbfdfe5a694e59288f8cf29dad77af5389a80/migrations/generic/default/1666001572785_remove_scheduled_stop_view/up.sql#L607)):*
> ```TSQL
> 
> -- note: removed the deleting part from the function, only doing the side-effects
> CREATE OR REPLACE FUNCTION service_pattern.delete_scheduled_stop_point() RETURNS trigger
> ```

Now that the function is not deleting the stop point anymore, maybe the name could be adjusted to reflect that?

How about `cleanup_removed_scheduled_stop_point_label` or similar?



_Code quote:_
```TSQL
delete_scheduled_stop_point
```
___
*[`migrations/generic/default/1666001572785_remove_scheduled_stop_view/up.sql` line 617 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-NFx_XbH2uiU4Bbd7VwA:-NFx_XbH2uiU4Bbd7VwB:bcqhz05) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/fc3fbfdfe5a694e59288f8cf29dad77af5389a80/migrations/generic/default/1666001572785_remove_scheduled_stop_view/up.sql#L617)):*
> ```TSQL
> 
> -- note: removed the inserting part from the function, only doing the side-effects
> CREATE OR REPLACE FUNCTION service_pattern.insert_scheduled_stop_point() RETURNS trigger
> ```

Same as above, maybe a new name could be used? `ensure_scheduled_stop_point_label_exists` ?



_Code quote:_
```TSQL
insert_scheduled_stop_point
```
___
*[`test/hasura/integration-tests/mutations/scheduled-stop-point/insert-with-id.spec.ts` line 7 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-NFxXu4M4qfteYTy6PJR:-NFxXu4M4qfteYTy6PJS:bk38q44) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/fc3fbfdfe5a694e59288f8cf29dad77af5389a80/test/hasura/integration-tests/mutations/scheduled-stop-point/insert-with-id.spec.ts#L7)):*
> ```XML
>   scheduledStopPoints,
> } from '@datasets/defaultSetup/scheduled-stop-points';
> import { getPropNameArray, queryTable, setupDb } from '@datasets/setup';
> ```

I guess automatic formatting / CI checking of the order might be a good idea, even though not in the scope of this PR.

So maybe it would have been nice to keep these re-orderings out of this PR, but I think it is not a show-stopper to have these included.



_Code quote:_
```XML
import { getPropNameArray, queryTable, setupDb } from '@datasets/setup';
import {
  LinkDirection,
  ScheduledStopPoint,
  ScheduledStopPointProps,
  VehicleMode,
} from '@datasets/types';
import * as dataset from '@util/dataset';
import '@util/matchers';

import { LocalDate } from 'local-date';
import * as pg from 'pg';
import * as rp from 'request-promise';
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[`test/hasura/integration-tests/mutations/scheduled-stop-point/insert-with-id.spec.ts` line 7 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-NFxXu4M4qfteYTy6PJR:-NG0fPBj7id8-axUrIfs:b-7bc5sg) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/fc3fbfdfe5a694e59288f8cf29dad77af5389a80/test/hasura/integration-tests/mutations/scheduled-stop-point/insert-with-id.spec.ts#L7)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I guess automatic formatting / CI checking of the order might be a good idea, even though not in the scope of this PR.

So maybe it would have been nice to keep these re-orderings out of this PR, but I think it is not a show-stopper to have these included.
</blockquote></details>

yeah, we could add a linter to this repo... I'll remove these changes from this PR

**Review by pallost — COMMENTED** [review]
no, I haven't... the privileges haven't changed but if the importer uses the internal_service_pattern.scheduled_stop_point table, then it should fix fixed to use the new schema

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-:-NG0nO7VE6O_3UjnsnWO:b-g4ah9j)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[`-- commits` line 7 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-NFxah40-4w5nXfCRWn7):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I suppose this line should be removed, since `insert_scheduled_stop_point_with_vehicle_mode` is left in the `internal_service_pattern`?
</blockquote></details>

Done.
___
*[`migrations/generic/default/1666001572785_remove_scheduled_stop_view/up.sql` line 607 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-NFx_CePE4b73aSlzvDi:-NG0nHfrDMHCFKV9NB2_:b-qaazo4) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/fc3fbfdfe5a694e59288f8cf29dad77af5389a80/migrations/generic/default/1666001572785_remove_scheduled_stop_view/up.sql#L607)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Now that the function is not deleting the stop point anymore, maybe the name could be adjusted to reflect that?

How about `cleanup_removed_scheduled_stop_point_label` or similar?
</blockquote></details>

renamed it to on_delete_scheduled_stop_point as it's now more of an event handler
___
*[`migrations/generic/default/1666001572785_remove_scheduled_stop_view/up.sql` line 617 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-NFx_XbH2uiU4Bbd7VwA:-NG0nLyh4-h-EVncNWv6:b-p3nfk6) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/fc3fbfdfe5a694e59288f8cf29dad77af5389a80/migrations/generic/default/1666001572785_remove_scheduled_stop_view/up.sql#L617)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Same as above, maybe a new name could be used? `ensure_scheduled_stop_point_label_exists` ?
</blockquote></details>

renamed it to on_insert_scheduled_stop_point as it's now more of an event handler

**Review by jschummer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/102#-:-NG1d2kV4ZG0dtzxianT:bnfp4nl)* status: 0 of 29 files reviewed, 1 unresolved discussion

**Pull request merged**
