### PR TITLE
Fix secret generation script on macOS

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/5)

### CODE REVIEW

**Review by pallost — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/5#-:-Mb152wS5C_h9ZLaa4WI:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haphut)

**Review by haphut — COMMENTED** [review]
Thanks for doing this, @tk-vincit ! Sorry for the delay in this review.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/5#-:-Mb5m1sC85vyIh1hLcru:b-y6sv49)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @tk-vincit)

___
*[generate-secrets-for-local-development.sh, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/5#-Mb5m0jR8bZbKylSfpSr:-Mb5m0jS8dnC6aHRuMSh:b-r13sz2) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/aa3fdf44240db97a4b8d90fdeeeb69ae0a3696cb/generate-secrets-for-local-development.sh#L27)):*
> ```Shell
>   # SIGPIPE ensues from writing into the pipe after the reading stops so use
>   # echo for pipefail.
>   export LC_CTYPE=C
> ```

Why is this set? I don't think it's a problem but I don't understand its purpose. Maybe there could be a comment for it.

And if it is meant for `tr`, it could be set in the subprocess so it would not "leak" out of this function:
`"$(LC_CTYPE=C </dev/urandom tr -dc ...`
___
*[generate-secrets-for-local-development.sh, line 54 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/5#-Mb5oIfVCI5_p02hC17v:-Mb5oIfVCI5_p02hC17w:b9fcc4l) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/aa3fdf44240db97a4b8d90fdeeeb69ae0a3696cb/generate-secrets-for-local-development.sh#L54)):*
> ```Shell
> 
> # Link the env files for running hasura-cli.
> ln -s "$(pwd)/${ENV_PATH}" "${HASURA_ENV_PATH}"
> ```

The script fails without the `-f` if it is run twice because `"${HASURA_ENV_PATH}"` exist already. So `rm -f` first.

Also, switching from a relative path to an absolute path breaks the link if the absolute path changes, for example if you move this project elsewhere in your local file system. I know I suggested that solution. :laughing: But if this works for you, maybe use this instead:
```sh
rm -f "${HASURA_ENV_PATH}"
ln -s \
  "$(
    realpath \
      --relative-to="$(dirname -- "${HASURA_ENV_PATH}")" \
      "${ENV_PATH}"
  )" \
  "${HASURA_ENV_PATH}"
```
If it doesn't, then don't bother with anything but the `rm -f`.

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/5)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @tk-vincit)

___
*[generate-secrets-for-local-development.sh, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/5#-Mb5m0jR8bZbKylSfpSr:-MbFXOgZ0MnbAAmi7OTY:bhry127) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/aa3fdf44240db97a4b8d90fdeeeb69ae0a3696cb/generate-secrets-for-local-development.sh#L27)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Why is this set? I don't think it's a problem but I don't understand its purpose. Maybe there could be a comment for it.

And if it is meant for `tr`, it could be set in the subprocess so it would not "leak" out of this function:
`"$(LC_CTYPE=C </dev/urandom tr -dc ...`
</blockquote></details>

Without it `tr` gives following error: `tr: Illegal byte sequence`

https://unix.stackexchange.com/questions/141420/tr-complains-of-illegal-byte-sequence

Anyway, your suggestion seems to work so I'll go with it. Thanks for the tip!
___
*[generate-secrets-for-local-development.sh, line 54 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/5#-Mb5oIfVCI5_p02hC17v:-MbFYKDs7AzHdvY7eO13:bs6jmtm) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/aa3fdf44240db97a4b8d90fdeeeb69ae0a3696cb/generate-secrets-for-local-development.sh#L54)):*
> ln -s \
>   "$(
>     realpath \
>       --relative-to="$(dirname -- "${HASURA_ENV_PATH}")" \
>       "${ENV_PATH}"
>   )" \
>   "${HASURA_ENV_PATH}"
`realpath: command not found` :disappointed: 
I could fix this locally by installing `coreutils`, but then it might not work with someone else :sweat_smile: 
So maybe I'll just add `rm -f` for now as you suggested.

**Review by haphut — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/5)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @tk-vincit)

**Pull request merged**
