### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65)

### CODE REVIEW

**Review by jarkkoka — COMMENTED** [review]
Basically looks pretty good to me. Left two comments.

> Reviewed 4 of 6 files at r1, 1 of 7 files at r4, 2 of 85 files at r5, 18 of 83 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-:-N14jA6I64PXA7UxrSLT:b306j6g)* status: 27 of 95 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @pallost)

___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 33 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N14iBvA4Wj2ay2vqoyi:-N14iBvA4Wj2ay2vqoyj:b-czr778) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0f6745dfbc81f4c2f78fed3aee39f094091df732/migrations/generic/default/1651038742404_localization/up.sql#L33)):*
> ```TSQL
> );
> CREATE INDEX ON localization.localized_texts (entity_id);
> CREATE INDEX ON localization.localized_texts (codeset_id);
> ```

Not sure whether these separate indices per column are needed when we already have a compound index for primary key (consisting of three columns). I think actual SELECT queries would utilise the primary key index since I would imagine that a real query would fetch all localized texts for a certain entity-codeset pair.



_Code quote:_
```TSQL
CREATE INDEX ON localization.localized_texts (entity_id);
CREATE INDEX ON localization.localized_texts (codeset_id);
CREATE INDEX ON localization.localized_texts (language_code);
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65)* status: 25 of 96 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 33 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N14iBvA4Wj2ay2vqoyi:-N18n_K1-PDkXpbQ_oXE:b-gdpa0s) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0f6745dfbc81f4c2f78fed3aee39f094091df732/migrations/generic/default/1651038742404_localization/up.sql#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Not sure whether these separate indices per column are needed when we already have a compound index for primary key (consisting of three columns). I think actual SELECT queries would utilise the primary key index since I would imagine that a real query would fetch all localized texts for a certain entity-codeset pair.
</blockquote></details>

These indexes are created so that JOINing would be efficient on these related tables. The compound primary key index is good only when searching for a given entry, but to my knowledge, it's not efficient when you'd like to use only a single column from the compound key (it's not indexed like that?)

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 1 of 83 files at r6, 3 of 3 files at r9, 10 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65)* status: 29 of 96 files reviewed, 4 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 33 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N14iBvA4Wj2ay2vqoyi:-N18xnDxEPCStwiEMLRb:b-ifmcbi) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0f6745dfbc81f4c2f78fed3aee39f094091df732/migrations/generic/default/1651038742404_localization/up.sql#L33)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

These indexes are created so that JOINing would be efficient on these related tables. The compound primary key index is good only when searching for a given entry, but to my knowledge, it's not efficient when you'd like to use only a single column from the compound key (it's not indexed like that?)
</blockquote></details>

Usually, when it comes to compound indices, the order of columns in the index matters. E.g. compound index may be used more efficiently in SQL queries if the columns picked in SELECTed fields appear (in the index) after the columns in WHERE predicate(s) because WHERE predicate(s) are evaluated in query execution before the result set fields are collected.

However, I think it is just safer or more convenient to include these individual indices in addition to compound index. Later on, it may be analysed whether indices need to be opimised based on actual queries executed in the app.
___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 11 at r10](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N18wWwm3-xczmG6A1Ct:-N18wWwm3-xczmG6A1Cu:biuyzax) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3002a3e3d989165d7691ba18d4add6afaea31267/migrations/generic/default/1651038742404_localization/up.sql#L11)):*
> ```TSQL
>   'List of languages in which the localized texts may come. Used as enum table';
> INSERT INTO localization.language (language_code)
>   VALUES ('en_US'), ('fi_FI'), ('sv_SV');
> ```

`sv_SV` is not a real locale identifier. Should be replaced with either `sv_FI` (Swedish-Finland)  or `sv_SE` (Swedish-Sweden).

But do we really need country codes in locale identifiers? I think sticking to just language codes may be sufficient. But are there any reasons e.g. in jore4-ui libs that justify including country code?



_Code quote:_
```TSQL
sv_SV
```
___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 20 at r10](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N18xExg8AeUwFSb-TV6:-N18xExg8AeUwFSb-TV7:b7t8ly) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3002a3e3d989165d7691ba18d4add6afaea31267/migrations/generic/default/1651038742404_localization/up.sql#L20)):*
> ```TSQL
>   CONSTRAINT unique_codeset_name UNIQUE (codeset_name)
> );
> COMMENT ON TABLE localization.codeset IS
> ```

Hmmm...Was thinking whether `localizable_item` OR `localized_item` would be a better table name in this schema. `codeset` term is more commonly used to express some applications constants that map to enum values (like vehicle mode).

Not a big deal anyway since the table is enclosed in a separate `localization` schema. Any opinions?



_Code quote:_
```TSQL
codeset
```
___
*[`migrations/seed-data/default/2524600800000_seed-routes/up.sql` line 20 at r9](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N18vRfS3bV9gDsyFDAi:-N18vRfS3bV9gDsyFDAj:b-kczdjl) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/efb8fd695050855eb09eb1aedf745eca5be66e9d/migrations/seed-data/default/2524600800000_seed-routes/up.sql#L20)):*
> ```TSQL
> VALUES
>   ('101f800c-39ed-4d85-8ece-187cd9fe1c5e', '02b5427a-98d0-4a15-9ba8-f7694b286c5a', 'fi_FI', 'Rautatientori - Veräjälaakso FI'),
>   ('101f800c-39ed-4d85-8ece-187cd9fe1c5e', '02b5427a-98d0-4a15-9ba8-f7694b286c5a', 'sv_SV', 'Rautatientori - Veräjälaakso SV'),
> ```

`sv_SV` is not a real locale identifier. In `sv_SV` locale identifier, `sv` is the language code part whereas `SV` is the country code part. However, `SV` is not a real country code. `FI` or `SE` are real country codes. But do we really need country codes in locale identifiers? Wouldn't language codes be just enough like using: `fi`, `sv`?



_Code quote:_
```TSQL
sv_SV
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65)* status: 29 of 96 files reviewed, 4 unresolved discussions (waiting on @jarkkoka)

___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 33 at r7](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N14iBvA4Wj2ay2vqoyi:-N197l4C4jXqgzlRvXSP:b-x4jsny) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/0f6745dfbc81f4c2f78fed3aee39f094091df732/migrations/generic/default/1651038742404_localization/up.sql#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Usually, when it comes to compound indices, the order of columns in the index matters. E.g. compound index may be used more efficiently in SQL queries if the columns picked in SELECTed fields appear (in the index) after the columns in WHERE predicate(s) because WHERE predicate(s) are evaluated in query execution before the result set fields are collected.

However, I think it is just safer or more convenient to include these individual indices in addition to compound index. Later on, it may be analysed whether indices need to be opimised based on actual queries executed in the app.
</blockquote></details>

OK, I'll keep them then, we can always drop them if things get bloated...
___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 11 at r10](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N18wWwm3-xczmG6A1Ct:-N198ttBDSXpvP4J-2HD:b-l4ku5w) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3002a3e3d989165d7691ba18d4add6afaea31267/migrations/generic/default/1651038742404_localization/up.sql#L11)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`sv_SV` is not a real locale identifier. Should be replaced with either `sv_FI` (Swedish-Finland)  or `sv_SE` (Swedish-Sweden).

But do we really need country codes in locale identifiers? I think sticking to just language codes may be sufficient. But are there any reasons e.g. in jore4-ui libs that justify including country code?
</blockquote></details>

good point, I'll fix it to se_SE!

It's a good practice however to use the full locale identifier. In our case it's not necessary, however it's more generic if other users of the datamodel can define separately en_US and en_UK for example. And yes, e.g. also the UI uses the full identifier when changing the user's language
___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 20 at r10](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N18xExg8AeUwFSb-TV6:-N199FCE4kvr4bcz68p-:beievrl) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3002a3e3d989165d7691ba18d4add6afaea31267/migrations/generic/default/1651038742404_localization/up.sql#L20)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Hmmm...Was thinking whether `localizable_item` OR `localized_item` would be a better table name in this schema. `codeset` term is more commonly used to express some applications constants that map to enum values (like vehicle mode).

Not a big deal anyway since the table is enclosed in a separate `localization` schema. Any opinions?
</blockquote></details>

'localized_item' sounds like it could refer to both the attribute name or the value itself. But I also don't like the 'codeset' term :) How would it sound to call it something like 'attribute_name'?
___
*[`migrations/seed-data/default/2524600800000_seed-routes/up.sql` line 20 at r9](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N18vRfS3bV9gDsyFDAi:-N197yNZ5YhUL8m_32CH:b-l4ku5w) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/efb8fd695050855eb09eb1aedf745eca5be66e9d/migrations/seed-data/default/2524600800000_seed-routes/up.sql#L20)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`sv_SV` is not a real locale identifier. In `sv_SV` locale identifier, `sv` is the language code part whereas `SV` is the country code part. However, `SV` is not a real country code. `FI` or `SE` are real country codes. But do we really need country codes in locale identifiers? Wouldn't language codes be just enough like using: `fi`, `sv`?
</blockquote></details>

good point, I'll fix it to se_SE!

It's a good practice however to use the full locale identifier. In our case it's not necessary, however it's more generic if other users of the datamodel can define separately en_US and en_UK for example. And yes, e.g. also the UI uses the full identifier when changing the user's language

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 3 of 83 files at r6, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65)* status: 32 of 96 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @pallost)

___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 11 at r10](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N18wWwm3-xczmG6A1Ct:-N19Amh82KM6ehtvOD8s:bl34ft6) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3002a3e3d989165d7691ba18d4add6afaea31267/migrations/generic/default/1651038742404_localization/up.sql#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

good point, I'll fix it to se_SE!

It's a good practice however to use the full locale identifier. In our case it's not necessary, however it's more generic if other users of the datamodel can define separately en_US and en_UK for example. And yes, e.g. also the UI uses the full identifier when changing the user's language
</blockquote></details>

Ok. No problem with using full locale identifiers. It may better fit the big picture (taking into account UI behavior). I would regard `sv_FI` more relevant to our app locality but don't mind `sv_SE` either?
___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 20 at r10](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N18xExg8AeUwFSb-TV6:-N19CzpQ6vuAAvJmRRhL:bnvuo1x) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/3002a3e3d989165d7691ba18d4add6afaea31267/migrations/generic/default/1651038742404_localization/up.sql#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

'localized_item' sounds like it could refer to both the attribute name or the value itself. But I also don't like the 'codeset' term :) How would it sound to call it something like 'attribute_name'?
</blockquote></details>

`attribute_name` could do as well. :+1:

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65)* status: 32 of 96 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 11 at r11](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N19FQITCe_5ckIimbm5:-N19FQITCe_5ckIimbm6:b5ad7gj) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1f2da380e3cb3175d8d5fbdabb9d106d8d248555/migrations/generic/default/1651038742404_localization/up.sql#L11)):*
> ```TSQL
>   'List of languages in which the localized texts may come. Used as enum table';
> INSERT INTO localization.language (language_code)
>   VALUES ('en_US'), ('fi_FI'), ('se_SE');
> ```

I think, `se_SE` is also a non-existent locale identifier. `sv_FI` would be more correct and IMO even better than `sv_SE` since in Finland we have different currency than in Sweden. Of course, the currency is not yet an issue but may be in the future when we advance into "compensation" module.



_Code quote:_
```TSQL
se_SE
```

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 3 of 83 files at r6, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65)* status: 35 of 96 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 23 at r12](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N1I8f3c4JM_UQ2GOPnq:-N1I8f3c4JM_UQ2GOPnr:b-4euxfh) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1594c20ae6df3dd15e01fc49074d23f813103408/migrations/generic/default/1651038742404_localization/up.sql#L23)):*
> ```TSQL
>   'List of attribute names which are used as localization keys';
> COMMENT ON COLUMN localization.attribute.attribute_name IS
>   'List of attribute names which are used as localization keys. Should be namespaced (e.g. "route_name")';
> ```

An attribute name that is used as localization key



_Code quote:_
```TSQL
List of attribute names which are used as localization keys
```
___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 35 at r12](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N1I92o820SF9MZ1rbXS:-N1I92o820SF9MZ1rbXT:bbb2gyw) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1594c20ae6df3dd15e01fc49074d23f813103408/migrations/generic/default/1651038742404_localization/up.sql#L35)):*
> ```TSQL
>   attribute_id uuid NOT NULL REFERENCES localization.attribute (attribute_id),
>   language_code text NOT NULL REFERENCES localization.language (language_code),
>   localized_text text,
> ```

Is there any reason to have null texts in the database? Then at least in the UI, a null-check may be need to be done even if a text item for a localization key is found. IMO a missing localization text could be implied by a missing database row.



_Code quote:_
```TSQL
text
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65)* status: 34 of 96 files reviewed, 2 unresolved discussions (waiting on @jarkkoka)

___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 23 at r12](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N1I8f3c4JM_UQ2GOPnq:-N1Ihmtc9Hb64zA_oaj3:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1594c20ae6df3dd15e01fc49074d23f813103408/migrations/generic/default/1651038742404_localization/up.sql#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

An attribute name that is used as localization key
</blockquote></details>

Done.
___
*[`migrations/generic/default/1651038742404_localization/up.sql` line 35 at r12](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65#-N1I92o820SF9MZ1rbXS:-N1IhnX3290VRdb_L4XM:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/1594c20ae6df3dd15e01fc49074d23f813103408/migrations/generic/default/1651038742404_localization/up.sql#L35)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Is there any reason to have null texts in the database? Then at least in the UI, a null-check may be need to be done even if a text item for a localization key is found. IMO a missing localization text could be implied by a missing database row.
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/65)* status: 35 of 96 files reviewed, all discussions resolved (waiting on @jarkkoka)

**Pull request merged**
