### PR TITLE
Rewrite localization migration to use jsonb fields

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70)* status: all files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`migrations/generic/default/1652181447341_localization_jsonb/up.sql` line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1mV5Vs0AKNdXuj1__V:-N1mV5Vs0AKNdXuj1__W:b-3imr1r) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a8e6f3b9e922c06b3100c8666c9600e63ef94021/migrations/generic/default/1652181447341_localization_jsonb/up.sql#L5)):*
> ```TSQL
> -- also set them NOT NULL as they are required fields
> ALTER TABLE route.line
>     ALTER COLUMN name_i18n SET DATA TYPE JSONB
> ```

Is `name_i18n` field missing `NOT NULL` constraint?



_Code quote:_
```TSQL
    ALTER COLUMN name_i18n SET DATA TYPE JSONB
      USING to_jsonb('{"fi_FI": "' || name_i18n || '"}'),
```
___
*[`migrations/generic/default/1652181447341_localization_jsonb/up.sql` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1mVMX49Ad_S3SeExe-:-N1mVMX49Ad_S3SeExe0:b-edglbm) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a8e6f3b9e922c06b3100c8666c9600e63ef94021/migrations/generic/default/1652181447341_localization_jsonb/up.sql#L10)):*
> ```TSQL
>       USING to_jsonb('{"fi_FI": "' || short_name_i18n || '"}'),
>     ALTER COLUMN short_name_i18n SET NOT NULL;
> CREATE INDEX idx_line_name_i18n on route.line USING gin (name_i18n);
> ```

Change `on` to uppercase letters => `ON` for all instances appearing in this file.



_Code quote:_
```TSQL
on
```
___
*[`migrations/generic/default/1652181447341_localization_jsonb/up.sql` line 215 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1mW1bj6a4ujyOghbWH:-N1mW1bj6a4ujyOghbWI:bgsy9ce) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a8e6f3b9e922c06b3100c8666c9600e63ef94021/migrations/generic/default/1652181447341_localization_jsonb/up.sql#L215)):*
> ```TSQL
> 
> -- fail migration for debugging
> -- DROP TABLE foo;
> ```

Unnecessary?



_Code quote:_
```TSQL
-- fail migration for debugging
-- DROP TABLE foo;
```

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70)* status: all files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`migrations/generic/default/1652181447341_localization_jsonb/up.sql` line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1mV5Vs0AKNdXuj1__V:-N1mY6x528iDuJBlrhjP:b-vdrd4z) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a8e6f3b9e922c06b3100c8666c9600e63ef94021/migrations/generic/default/1652181447341_localization_jsonb/up.sql#L5)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Is `name_i18n` field missing `NOT NULL` constraint?
</blockquote></details>

it already has NOT NULL constraint from previous migrations. Should I add it here too as a clarification?
___
*[`migrations/generic/default/1652181447341_localization_jsonb/up.sql` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1mVMX49Ad_S3SeExe-:-N1mYOr-DeWqjYYJ_ITQ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a8e6f3b9e922c06b3100c8666c9600e63ef94021/migrations/generic/default/1652181447341_localization_jsonb/up.sql#L10)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Change `on` to uppercase letters => `ON` for all instances appearing in this file.
</blockquote></details>

Done.
___
*[`migrations/generic/default/1652181447341_localization_jsonb/up.sql` line 215 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1mW1bj6a4ujyOghbWH:-N1mYQ7IALOUAbG1OTS2:b-i4uc8f) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a8e6f3b9e922c06b3100c8666c9600e63ef94021/migrations/generic/default/1652181447341_localization_jsonb/up.sql#L215)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Unnecessary?
</blockquote></details>

this is only for debugging for now, it'll be removed when I finalize these migrations

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @jarkkoka)

___
*[`migrations/generic/default/1652181447341_localization_jsonb/up.sql` line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1mV5Vs0AKNdXuj1__V:-N1rlHMm5tECfJ_iiTcE:bv8o8mf) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a8e6f3b9e922c06b3100c8666c9600e63ef94021/migrations/generic/default/1652181447341_localization_jsonb/up.sql#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it already has NOT NULL constraint from previous migrations. Should I add it here too as a clarification?
</blockquote></details>

added it as a clarification
___
*[`migrations/generic/default/1652181447341_localization_jsonb/up.sql` line 215 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1mW1bj6a4ujyOghbWH:-N1rlDaU20hEuV5PKL6i:b-hfpv0l) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a8e6f3b9e922c06b3100c8666c9600e63ef94021/migrations/generic/default/1652181447341_localization_jsonb/up.sql#L215)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is only for debugging for now, it'll be removed when I finalize these migrations
</blockquote></details>

removed

**Review by HenrikHartiala — COMMENTED** [review]
> Reviewed 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70)* status: all files reviewed, 6 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[`integration-test/datasets/factories.ts` line 5 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1wxQRaCWDS1KkLd0kC:-N1wxQRaCWDS1KkLd0kD:b-y66dr0) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/17847aced61abfdc1fb76990d37c1ba678dba163/integration-test/datasets/factories.ts#L5)):*
> ```XML
> export const buildLocalizedString = (str: string): LocalizedString => ({
>   fi_FI: str,
>   sv_FI: str,
> ```

Should we add some constant `SV` to the sv_FI  string to help check that the localizations differ from each other?
___
*[`integration-test/datasets/factories.ts` line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1wxT_DAs4yQ2EbPYeT:-N1wxT_DAs4yQ2EbPYeU:b-6of1yn) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/17847aced61abfdc1fb76990d37c1ba678dba163/integration-test/datasets/factories.ts#L20)):*
> ```XML
> 
> export const buildLine = (label: string, vehicleMode: VehicleMode) => ({
>   label: `${label}`,
> ```

I think the string literal is not needed here. 
___
*[`migrations/generic/default/1652271641913_localization_jsonb/up.sql` line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1wz_J3BKU8aUl-aIv3:-N1wz_J40RZLsNweJ4n9:b2vjtq3) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/17847aced61abfdc1fb76990d37c1ba678dba163/migrations/generic/default/1652271641913_localization_jsonb/up.sql#L6)):*
> ```TSQL
> ALTER TABLE route.line
>     ALTER COLUMN name_i18n SET DATA TYPE JSONB
>       USING to_jsonb('{"fi_FI": "' || name_i18n || '"}'),
> ```

I was just wondering that should the sv_FI be populated with the same value, or does it matter at this point? Maybe it is more clear that it is undefined if there actually is not a translation.

**Review by jarkkoka — COMMENTED** [review]
Basically, looks good to me. Had a look at mainly earlier comments and their replies.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-:-N1x7SUq-2tiEBo3dbmW:b-zufv0)* status: all files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[`migrations/generic/default/1652181447341_localization_jsonb/up.sql` line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1mV5Vs0AKNdXuj1__V:-N1x6u2M8s5pcvP2aU5j:b3r1nna) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/a8e6f3b9e922c06b3100c8666c9600e63ef94021/migrations/generic/default/1652181447341_localization_jsonb/up.sql#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

added it as a clarification
</blockquote></details>

Ok, thanks for clarification!

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`integration-test/datasets/factories.ts` line 5 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1wxQRaCWDS1KkLd0kC:-N2BgpbU9tkdlpabpw-e:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/17847aced61abfdc1fb76990d37c1ba678dba163/integration-test/datasets/factories.ts#L5)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Should we add some constant `SV` to the sv_FI  string to help check that the localizations differ from each other?
</blockquote></details>

Done
___
*[`integration-test/datasets/factories.ts` line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1wxT_DAs4yQ2EbPYeT:-N2Bgsbn4tnorothv_ve:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/17847aced61abfdc1fb76990d37c1ba678dba163/integration-test/datasets/factories.ts#L20)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think the string literal is not needed here. 
</blockquote></details>

Done
___
*[`migrations/generic/default/1652271641913_localization_jsonb/up.sql` line 6 at r2](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-N1wz_J3BKU8aUl-aIv3:-N2BgvMy0_NNpp7GlvJP:bjg467q) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/17847aced61abfdc1fb76990d37c1ba678dba163/migrations/generic/default/1652271641913_localization_jsonb/up.sql#L6)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I was just wondering that should the sv_FI be populated with the same value, or does it matter at this point? Maybe it is more clear that it is undefined if there actually is not a translation.
</blockquote></details>

Yeah, I just wanted that this string becomes a json object... We cannot automate however the translation to Swedish text

**Review by HenrikHartiala — APPROVED** [review]
Nice work!

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/70#-:-N2BianU7v2epEwTuYHs:bdtx8r6)* status: 20 of 22 files reviewed, all discussions resolved (waiting on @HenrikHartiala)

**Pull request merged**
