### PR TITLE
Add SQL function to calculate distances between stop points in journey pattern

### PR DESCRIPTION
**Pull request by jarkkoka**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJEiGjmEpjOnccbmJ0B:-NJEiGjmEpjOnccbmJ0C:b-ezkuro) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L12)):*
> ```TSQL
> $$
> SELECT route_id
> FROM route.route r
> ```

no need to create the "r" alias if you don't use it
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 52 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJEjA_8BvmtviqPH355:-NJEjA_96u4FUJZtu41G:b6pehw9) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L52)):*
> ```TSQL
>   JOIN service_pattern.scheduled_stop_point ssp USING (label)
>   WHERE sspijp.journey_pattern_id = filter_journey_pattern_id
>     AND ssp.priority < internal_utils.const_priority_draft()
> ```

I'd actually move this `WITH` section to its own function as it's a pretty reusable code block. It would also certainly be useful for the UI to list the effective stop instances for a given journey pattern. That function should have parameters (journey_pattern_id uuid, observation_date date, include_draft_stops boolean) and should return ssp_in_jp rows enriched with an "effective_scheduled_stop_point_id" column
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 66 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJEkhfB8UlTUKgMvXE1:-NJEkhfC7qf0NrW0PJXi:b-zcvi1l) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L66)):*
> ```TSQL
>   timing_place_id
> FROM unambiguous_sspijp sspijp
> JOIN service_pattern.scheduled_stop_point ssp USING (scheduled_stop_point_id)
> ```

you don't seem to be using the "sspijp" and "ssp" aliases. Personally I like to use them to see explicitly which column comes from what table. Your choice: either use the aliases or don't create them

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 1 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJFNm--7sbiYA0WP0pk:-NJFNm--7sbiYA0WP0pl:b-9k52id) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L1)):*
> ```TSQL
> CREATE OR REPLACE FUNCTION route.find_route_ids(
> ```

not necessarily in the scope of this PR, but you should update the hasura metadata to make these functions callable from the graphql endpoint
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 72 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJFO3Hk-ZRmHQpnGSoJ:-NJFNnfN5A1lm4NId6i3:b-pkque1) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L72)):*
> ```TSQL
> 
> 
> CREATE OR REPLACE FUNCTION service_pattern.get_distances_between_stop_points(
> ```

If I understand correctly, this function takes an array of journey patterns as a parameter, probably to optimize the query...? However taking multiple journey patterns as an input makes the logic harder to read and I don't think it makes things that much faster. I'd only take a single journey pattern at a time
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 113 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJFOuYi40PfbyTTWJyv:-NJFOuYi40PfbyTTWJyw:b-3rag92) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L113)):*
> ```TSQL
>     sspi.stop_point_location,
> 
>     -- It is assumed, that we stop at the first matching infrastructure link.
> ```

thanks for the comment!
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 135 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJFPuH_4iAfoR3o1jOT:-NJFPuHaDGbJcIT2-qQ_:b-nsporv) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L135)):*
> ```TSQL
>   JOIN route.infrastructure_link_along_route ilar USING (route_id, infrastructure_link_id)
>   WHERE sspi.stop_point_sequence = 1
>     AND (
> ```

I wonder if we already have a convenience utility function for checking the compatibility of the stop direction and the infra link direction. Might be sensible to create one... *could just take the direction string and the is_traversal_forwards boolean directly

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @culka and @pallost)

___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 12 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJEiGjmEpjOnccbmJ0B:-NJniZYK48IW_e0JY5n9:b-focqmb) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

no need to create the "r" alias if you don't use it
</blockquote></details>

Oh, yes. Will take it away.
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 52 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJEjA_8BvmtviqPH355:-NJzHZvU0AYIgyVqg6dx:b-z39wak) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L52)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd actually move this `WITH` section to its own function as it's a pretty reusable code block. It would also certainly be useful for the UI to list the effective stop instances for a given journey pattern. That function should have parameters (journey_pattern_id uuid, observation_date date, include_draft_stops boolean) and should return ssp_in_jp rows enriched with an "effective_scheduled_stop_point_id" column
</blockquote></details>

Thanks for such a concrete improvement suggestion. I will implement this change.
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 66 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJEkhfB8UlTUKgMvXE1:-NJzHo1Y6JA8VPil41W9:b-mobetr) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L66)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you don't seem to be using the "sspijp" and "ssp" aliases. Personally I like to use them to see explicitly which column comes from what table. Your choice: either use the aliases or don't create them
</blockquote></details>

Ok, I will be more explicit about column sources.
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 72 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJFO3Hk-ZRmHQpnGSoJ:-NJzHv9o2NIYCmyoVEhk:b-unxbsn) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L72)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

If I understand correctly, this function takes an array of journey patterns as a parameter, probably to optimize the query...? However taking multiple journey patterns as an input makes the logic harder to read and I don't think it makes things that much faster. I'd only take a single journey pattern at a time
</blockquote></details>

Well, actually this is an intermediary function that should not be called directly via the GraphQL API or even by SQL clients. In terms of modularity, I made this journey pattern-based interface for ease of testing.
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 113 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJFOuYi40PfbyTTWJyv:-NJzIkacCSRrpjmQK9N0:basvvxk) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L113)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

thanks for the comment!
</blockquote></details>

Glad you found it useful!
___
*[`migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql` line 135 at r3](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-NJFPuH_4iAfoR3o1jOT:-NJzJBUf8t5LsB2jxNNX:b7vt6n7) ([raw file](https://github.com/hsldevcom/jore4-hasura/blob/385be0aff49f1ccf1c072cea44f2295ba9dc6b5e/migrations/generic/default/2000000000007_R_after_migrate_add_fn_to_calculate_stop_interval_lengths/up.sql#L135)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I wonder if we already have a convenience utility function for checking the compatibility of the stop direction and the infra link direction. Might be sensible to create one... *could just take the direction string and the is_traversal_forwards boolean directly
</blockquote></details>

I prefer to do it in a separate PR because it probably requires changes to other migration files as well. Or what do you think?

**Review by culka — APPROVED** [review]
Looking really good, everything is clearly commented and the tests test what they should. :lgtm: 

> Reviewed 3 of 8 files at r3, 2 of 5 files at r4, 2 of 8 files at r5, 5 of 7 files at r6, 1 of 12 files at r8, 9 of 12 files at r10, 3 of 7 files at r11, 1 of 2 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-hasura/116#-:-NLvZ07F1mAyE9jl7zdt:b-sclu6n)* status: all files reviewed, 7 unresolved discussions (waiting on @jarkkoka and @pallost)

**Pull request merged**
