### PR TITLE
Add tests for substitute operating period

### PR DESCRIPTION
**Pull request by Perholehto**
- Tests for adding, editing and deleting
- Tests also database constraints related to substitute operating period

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195)

### CODE REVIEW

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195)* status: 0 of 2 files reviewed, 13 unresolved discussions (waiting on @Perholehto)

___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbrnWOH4RRtWuH-wvid:-NbrnWOH4RRtWuH-wvie:b-n51yjo) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L23)):*
> ```XML
> };
> 
> const buildPartialEditSubstituteOperatingPeriodMutation = (
> ```

This feels like made for quite a specific use case and not very reusable. I would maybe rather split these to individual parts and compose final mutation from those in the test suites. That's kind of the point why these are "parital" mutations in the first place. So in the related suite you could make some helper function like this:
```
const buildEditSubsituteOperatingPeriodMutation = (input: {
  periodsToInsert: Partial<SubstituteOperatingPeriod>[];
  periodsToDelete: UUID[];
  daysToInsert: Partial<SubstituteOperatingDayByLineType>[];
}) =>
  wrapWithTimetablesMutation(`
    ${buildPartialInsertSubstituteOperatingPeriod(periodsToInsert}
    ${buildPartialDeleteSubstituteOperatingDayByLineType(periodsToDelete}
    ${buildPartialInsertSubstituteOperatingDayByLineType(daysToInsert}
  `)
);
```
___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 51 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbrmjgH9uk8NupQF7aG:-NbrmjgI2J-LaZqjlrlH:b-4hvdmu) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L51)):*
> ```XML
>     affected_rows
>     }
>   `;
> ```

Indentations here could use some adjustment (Prettier doesn't touch them since these are just strings):



_Suggestion:_
```XML
) => `
  timetables_insert_service_calendar_substitute_operating_period(
    objects: ${periodsToInsert.map((p) => toGraphQlObject(p))}
    on_conflict: {
      constraint: substitute_operating_period_pkey
      update_columns: [period_name]
    }
  ) {
    affected_rows
  }

  timetables_delete_service_calendar_substitute_operating_day_by_line_type(
    where: {
      substitute_operating_period_id: {
        _in: ${JSON.stringify(periodsToDelete,)}
      }
    }
  ) {
    affected_rows
  }

  timetables_insert_service_calendar_substitute_operating_day_by_line_type(
    objects: ${daysToInsert.map((d) => toGraphQlObject(d, ['type_of_line']))}
  ) {
    affected_rows
  }
`;
```
___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 61 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbscHsV0CS-3IAjlXTK:-NbscHsW50r8RS-SRlbh:bhcc0xl) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L61)):*
> ```XML
>         affected_rows
>       }
>   `;
> ```

Same here, improve indentations, eg:



_Suggestion:_
```XML
) =>`
  timetables_delete_service_calendar_substitute_operating_period(
    where: {
      substitute_operating_period_id: { _in: ${JSON.stringify(ids)} }
    }
  ) {
    affected_rows
  }
`;
```
___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 70 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbscZcrEgmplYCkDc8E:-NbscZcrEgmplYCkDc8F:b-qn21p6) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L70)):*
> ```XML
>   ) {
>     affected_rows
>   }`;
> ```

And here, eg:



_Suggestion:_
```XML
) => `
  timetables_insert_service_calendar_substitute_operating_period(
    objects: [
      ${toGraphQlObject(objects[0], ['type_of_line'])}
    ]
  ) {
    affected_rows
  }
`;
```
___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 72 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbrpV1bDBgXmAAefS9K:-NbrpV1cD3WuGr9RtR1K:b-nl9kkv) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L72)):*
> ```XML
>   }`;
> 
> export const buildDeleteSubstituteOperatingPeriodMutation = (
> ```

I think it would be ok to omit these complete functions and do the wrapping in suites. Eg. this one is only used once.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 31 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsTfQn2FSiOo83VVd_:-NbsTfQn2FSiOo83VVda:b-kveuev) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L31)):*
> ```XML
>   beforeAll(() => {
>     dbConnection = createDbConnection(timetablesDbConfig);
>     builtDataset = buildHslTimetablesDataset(defaultTimetablesDataset);
> ```

FYI  the dataset could also be built outside the beforeAll just fine. But no harm doing it here either (besides one extra line of code) so no need to change.w
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 62 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsU0EX595aFNPOZ7kj:-NbsU0EYBTYNJzK47Kol:b-5pifab) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L62)):*
> ```XML
>     const dayRes = await getSubstituteOperatingDaysByLineTypes();
>     const daysBeforeDelete = dayRes.rowCount;
>     return [periodsBeforeDelete, daysBeforeDelete];
> ```

I think it would be clearer to return these as object, since order of the values in an array is not very explicit (even if period is the parent of days):
```
return { periodsCount, daysCount }
```

Also, maybe remove the "before delete" naming from inside this function. Could be called in other contexts as well than just before delete, right?
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 66 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsTHrD1UGIDRXRe-ic:-NbsTHrD1UGIDRXRe-id:b-d4mnsj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L66)):*
> ```XML
> 
>   describe('Insert substitute operating period', () => {
>     it('Period with one substitute day', async () => {
> ```

Typically I would name test cases so they can be "read aloud", as in (`it('should insert period with one substitute day'` reads `it should insert...`. Though don't think we've been 100% strict about that.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 67 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsXTe928avF6F5QfDi:-NbsXTeAAsYBSHMgMmTz:b-dprr41) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L67)):*
> ```XML
>   describe('Insert substitute operating period', () => {
>     it('Period with one substitute day', async () => {
>       const [periodCountBefore, dayCountBefore] = await getRowCounts();
> ```

This before version is done in every test here. Could maybe do it in beforeEach?
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 101 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsVBsG2SjC5j4TOO7X:-NbsVBsG2SjC5j4TOO7Y:b-30ss7f) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L101)):*
> ```XML
>             type_of_line: TypeOfLine.CityTramService,
>             superseded_date: DateTime.fromISO('2023-05-20'),
>             substitute_day_of_week: 7,
> ```

Elsewhere we've used enum mapping for these: 



_Suggestion:_
```XML
substitute_day_of_week: DayOfWeek.Sunday,
```
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 203 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsTZPg-Dvv2HKfngoR:-NbsTZPg-Dvv2HKfngoS:b-708n1a) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L203)):*
> ```XML
>     });
> 
>     describe('unique dow', () => {
> ```

Would rather not use abbreviations (especially lowercase) in suite names. This is "day of week" I take it?
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 270 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-Nbs_njJ75kxPiJobone:-Nbs_njK6a9YvPDXOqUE:b-i6lhyn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L270)):*
> ```XML
>         const inputData = {
>           is_preset: false,
>           period_name: 'TODO',
> ```

TODO, not that this matters.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 441 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsZl0bDXiVbMYxnGIc:-NbsZl0bDXiVbMYxnGId:bicazmj) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L441)):*
> ```XML
>       });
>     });
>     it('End time must be within the time limits of the operating day', async () => {
> ```

Newline before each it/describe.

We should really add a lint for this. Had similar comment with Henkka at https://github.com/HSLdevcom/jore4-hasura/pull/193
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 473 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsbQcJ9wecCinStpbW:-NbsbQcKEGxhYpdOXTe8:bw8bane) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L473)):*
> ```XML
> 
>   describe('Edit substitute operating period', () => {
>     it('Edit period changes days by line type correctly', async () => {
> ```

Is the point here to test that period update and day insert work in same transaction? If so, the test name should probably reflect that. If not, then this test does to much.

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195)* status: 0 of 2 files reviewed, 13 unresolved discussions (waiting on @Leitsi)

___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbrnWOH4RRtWuH-wvid:-NbwwP9TBo5zkgaP07A-:b6fszie) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L23)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This feels like made for quite a specific use case and not very reusable. I would maybe rather split these to individual parts and compose final mutation from those in the test suites. That's kind of the point why these are "parital" mutations in the first place. So in the related suite you could make some helper function like this:
```
const buildEditSubsituteOperatingPeriodMutation = (input: {
  periodsToInsert: Partial<SubstituteOperatingPeriod>[];
  periodsToDelete: UUID[];
  daysToInsert: Partial<SubstituteOperatingDayByLineType>[];
}) =>
  wrapWithTimetablesMutation(`
    ${buildPartialInsertSubstituteOperatingPeriod(periodsToInsert}
    ${buildPartialDeleteSubstituteOperatingDayByLineType(periodsToDelete}
    ${buildPartialInsertSubstituteOperatingDayByLineType(daysToInsert}
  `)
);
```
</blockquote></details>

This makes sense. Refactored these to individual parts and test suite takes care of the rest.
___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 51 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbrmjgH9uk8NupQF7aG:-Nbx8DWeB1cldS4fl3nY:b-ci3ik0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L51)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Indentations here could use some adjustment (Prettier doesn't touch them since these are just strings):
</blockquote></details>

Yeah, that's ugly, this happens when you are used that Prettier will make everything pretty...
___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 61 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbscHsV0CS-3IAjlXTK:-Nbx8UZG6Yo3-uRxF7W9:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L61)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Same here, improve indentations, eg:
</blockquote></details>

Done.
___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 70 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbscZcrEgmplYCkDc8E:-Nbx8_UlAolPY-9hEdv3:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L70)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

And here, eg:
</blockquote></details>

Done.
___
*[`test/hasura/hsl/timetablesdb/mutations.ts` line 72 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbrpV1bDBgXmAAefS9K:-NbtBd974kpGh8MYCm75:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/mutations.ts#L72)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I think it would be ok to omit these complete functions and do the wrapping in suites. Eg. this one is only used once.
</blockquote></details>

Done.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 62 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsU0EX595aFNPOZ7kj:-NbwvqdT0htjJ8JhnfFZ:b-or87pn) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L62)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I think it would be clearer to return these as object, since order of the values in an array is not very explicit (even if period is the parent of days):
```
return { periodsCount, daysCount }
```

Also, maybe remove the "before delete" naming from inside this function. Could be called in other contexts as well than just before delete, right?
</blockquote></details>

Changed to return object instead of array. Changed also naming that is leftovers for bad refactoring...
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 66 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsTHrD1UGIDRXRe-ic:-Nbx9S3fCz2gOhY36990:b-2w6l7c) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L66)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Typically I would name test cases so they can be "read aloud", as in (`it('should insert period with one substitute day'` reads `it should insert...`. Though don't think we've been 100% strict about that.
</blockquote></details>

I agree with naming and changed pretty much all names for test cases. Do you know if this is mentioned in a some form of a document? 
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 67 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsXTe928avF6F5QfDi:-Nbww5T31nmSqN5DIsRw:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L67)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This before version is done in every test here. Could maybe do it in beforeEach?
</blockquote></details>

Done.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 101 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsVBsG2SjC5j4TOO7X:-Nbww6jQBLAVilBdDzYZ:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L101)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Elsewhere we've used enum mapping for these:
</blockquote></details>

Done.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 203 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsTZPg-Dvv2HKfngoR:-NbxARR81jqOvGWxxIIe:btqqu58) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L203)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Would rather not use abbreviations (especially lowercase) in suite names. This is "day of week" I take it?
</blockquote></details>

Correct!
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 270 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-Nbs_njJ75kxPiJobone:-NbxZLo58-k7w0hbuP0k:b-vgaftq) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L270)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

TODO, not that this matters.
</blockquote></details>

Not really, but added a "better" name.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 441 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsZl0bDXiVbMYxnGIc:-NbwwCeg7d4eNLv8Nxn_:b-c7dlht) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L441)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Newline before each it/describe.

We should really add a lint for this. Had similar comment with Henkka at https://github.com/HSLdevcom/jore4-hasura/pull/193
</blockquote></details>

Do we have ticket about adding this to the linter?
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 473 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsbQcJ9wecCinStpbW:-NbxYt1K179Hn2ohfX2d:bvt21vf) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L473)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Is the point here to test that period update and day insert work in same transaction? If so, the test name should probably reflect that. If not, then this test does to much.
</blockquote></details>

This is just a happy case. Added case for testing that rollback happens.

**Review by Leitsi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Perholehto)

___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 66 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsTHrD1UGIDRXRe-ic:-NbxaRFX0y6qC4NQInNE:b-xrdlvo) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L66)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I agree with naming and changed pretty much all names for test cases. Do you know if this is mentioned in a some form of a document?
</blockquote></details>

I don't think so. This is just how I've learned to do, and seems to generally be applied in our repositories as well. My understanding has been this is quite typical practice in JS/TS world, eg. quick googling lead me to this which describes this naming practice: https://github.com/mawrkus/js-unit-testing-guide#-name-your-tests-properly
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 441 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsZl0bDXiVbMYxnGIc:-NbxeF3S6bdxpCI_WEth:bq9ysp6) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L441)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Do we have ticket about adding this to the linter?
</blockquote></details>

Henkka seems to have added this, case closed.

Though, the newline is still missing here :)
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 85 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbxcvDaAD8zvvoCBnQB:-NbxcvDaAD8zvvoCBnQC:b-crtrw0) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/570059bc55143f1f2e049b97cd11b1229c6e4ac7/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L85)):*
> ```XML
>       );
> 
>     it('should add period and days by line type correctly', async () => {
> ```

`add` sounds like an arithmetical operation, maybe rather `insert` or `create`
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 147 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbxeuK606As5NvnB8hg:-NbxeuK606As5NvnB8hh:b-h1r6n6) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/570059bc55143f1f2e049b97cd11b1229c6e4ac7/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L147)):*
> ```XML
> 
>     describe('overlapping time ranges for line types', () => {
>       it('should throw error when time ranges overlap with line type', async () => {
> ```

I think `should throw an error` is slightly better English.

Or, `should fail`.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 241 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbxdMVr6Tm1DDNWAzEg:-NbxdMVr6Tm1DDNWAzEh:undefined) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/570059bc55143f1f2e049b97cd11b1229c6e4ac7/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L241)):*
> ```XML
> 
>     describe('unique day of week', () => {
>       it('should allow same day of week and type of line when time range do not overlap', async () => {
> ```





_Suggestion:_
```XML
it('should allow same day of week and type of line when time ranges do not overlap', async () => {
```

**Review by Perholehto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 66 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsTHrD1UGIDRXRe-ic:-NbxjKHb4akhGup_pDz4:b-8q6zav) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L66)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I don't think so. This is just how I've learned to do, and seems to generally be applied in our repositories as well. My understanding has been this is quite typical practice in JS/TS world, eg. quick googling lead me to this which describes this naming practice: https://github.com/mawrkus/js-unit-testing-guide#-name-your-tests-properly
</blockquote></details>

Yeah, maybe this is so standard nowadays that it isn't worth of a mention :)
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 441 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbsZl0bDXiVbMYxnGIc:-Nbxh3kf-GxTjKGvMfSd:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/5d279d593f44e3272a33d868d929346ce4e70bcf/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L441)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Henkka seems to have added this, case closed.

Though, the newline is still missing here :)
</blockquote></details>

Done.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 85 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbxcvDaAD8zvvoCBnQB:-NbxgqSP2bwMrrl1YkTq:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/570059bc55143f1f2e049b97cd11b1229c6e4ac7/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L85)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

`add` sounds like an arithmetical operation, maybe rather `insert` or `create`
</blockquote></details>

Done.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 147 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbxeuK606As5NvnB8hg:-NbxgmpY6QvEUJLo38ga:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/570059bc55143f1f2e049b97cd11b1229c6e4ac7/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L147)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I think `should throw an error` is slightly better English.

Or, `should fail`.
</blockquote></details>

Done.
___
*[`test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts` line 241 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hasura/195#-NbxdMVr6Tm1DDNWAzEg:-Nbxgv4a3V5HEn5lNlhK:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hasura/blob/570059bc55143f1f2e049b97cd11b1229c6e4ac7/test/hasura/hsl/timetablesdb/integration-tests/substitute-operating-periods/substitute-operating-period.spec.ts#L241)):*
> ```XML
> 
>     describe('unique day of week', () => {
>       it('should allow same day of week and type of line when time range do not overlap', async () => {
> ```

Done.

**Pull request merged**
